### ISSUE TITLE
com.google.android.gms.ads.internal.formats.z.a(:com.google.android.gms.DynamiteModulesA@11951440:208)

### ISSUE THREAD

**Issue by mutour** [googleads/googleads-mobile-android-examples#101]
```
java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.Map.containsKey(java.lang.Object)' on a null object reference
            at com.google.android.gms.ads.internal.formats.z.a(:com.google.android.gms.DynamiteModulesA@11951440:208)
            at com.google.android.gms.ads.internal.formats.aa.run(:com.google.android.gms.DynamiteModulesA@11951440:36)
            at android.os.Handler.handleCallback(Handler.java:761)
            at android.os.Handler.dispatchMessage(Handler.java:98)
            at android.os.Looper.loop(Looper.java:156)
            at android.app.ActivityThread.main(ActivityThread.java:6523)
            at java.lang.reflect.Method.invoke(Native Method)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
```

最近开发的新产品频繁出现这个崩溃，不清楚原因是什么，ads用的是11.6.0版本，之前11.0.0版本也出现过这个问题，界面采用高级原生的NativeAppInstallAdView和NativeContentAdView，麻烦看下该怎么解决，出错原因是什么？

**Comment by ericleich** [comment]
Closing this issue due to it being a crash in the Google Mobile Ads SDK itself, not in samples.

This particular crash should have been fixed in Google Play services 11.0.0. If this is happening with newer versions, please reach out to the [Google Mobile Ads SDK developer forum](groups.google.com/group/google-admob-ads-sdk) for additional support.
