### ISSUE TITLE
Crash while loading Native Ads

### ISSUE THREAD

**Issue by bantyK** [googleads/googleads-mobile-android-examples#117]
My app is crashing continuously while loading native custom template ad with the following exceptions`java.lang.OutOfMemoryError: Failed to allocate a 4665612 byte allocation with 2452736 free bytes and 2MB until OOM
      
  at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
        at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
        at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:646)
        at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:622)
        at com.google.android.gms.ads.internal.renderer.nativeads.e.b(:com.google.android.gms.dynamite_dynamitemodulesa@12529020@12.5.29 (040308-192802242):10)
        at com.google.android.gms.ads.internal.renderer.nativeads.e.a(:com.google.android.gms.dynamite_dynamitemodulesa@12529020@12.5.29 (040308-192802242):29)
        at com.google.android.gms.ads.internal.util.bc.a(:com.google.android.gms.dynamite_dynamitemodulesa@12529020@12.5.29 (040308-192802242):4)
        at com.google.android.gms.ads.internal.util.future.i.run(Unknown Source)
        at com.google.android.gms.ads.internal.util.future.ad.execute(:com.google.android.gms.dynamite_dynamitemodulesa@12529020@12.5.29 (040308-192802242):2)
        at com.google.android.gms.ads.internal.util.future.y.run(Unknown Source)
        at com.google.android.gms.ads.internal.util.future.x.a(:com.google.android.gms.dynamite_dynamitemodulesa@12529020@12.5.29 (040308-192802242):20)
        at com.google.android.gms.ads.internal.util.future.af.b(:com.google.android.gms.dynamite_dynamitemodulesa@12529020@12.5.29 (040308-192802242):18)
        at com.google.android.gms.ads.internal.util.bh.a(:com.google.android.gms.dynamite_dynamitemodulesa@12529020@12.5.29 (040308-192802242):19)
        at dq.run(:com.google.android.gms.dynamite_dynamitemodulesa@12529020@12.5.29 (040308-192802242):10)
        at android.os.Handler.handleCallback(Handler.java:751)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6123)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:867)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:757)`

How to avoid this?

**Comment by stowy** [comment]
Hi, thanks for your query.

These github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including steps showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
