### ISSUE TITLE
The sample code doesn't seem to work.

### ISSUE THREAD

**Issue by huymc** [googleads/googleads-mobile-android-examples#127]
Hi, i am using your sample code but it doesn't seem to work. The sample ad doesn't show at all. This is the [url](https://github.com/googleads/googleads-mobile-android-examples/tree/master/java/admob/BannerExample).  Can somebody help?

**Comment by ericleich** [comment]
Just tried on my end and it still works. I'm guessing it's an ad fill problem. Which country are you requesting ads from?

**Comment by mertkanu** [comment]
Hi, I'm also having an issue with rewarded video ads; here's the logs:

> com.google.android.gms.example.rewardedvideoexample E/ExoPlayerImplInternal: Internal track renderer error.
    com.google.android.gms.ads.exoplayer1.d: com.google.android.gms.ads.exoplayer1.upstream.m: java.io.EOFException
        at com.google.android.gms.ads.exoplayer1.p.b(:com.google.android.gms.dynamite_dynamitemodulesa@12685026@12.6.85 (040700-197041431):21)
        at com.google.android.gms.ads.exoplayer1.i.handleMessage(:com.google.android.gms.dynamite_dynamitemodulesa@12685026@12.6.85 (040700-197041431):65)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
        at com.google.android.gms.ads.exoplayer1.util.h.run(:com.google.android.gms.dynamite_dynamitemodulesa@12685026@12.6.85 (040700-197041431):5)
     Caused by: com.google.android.gms.ads.exoplayer1.upstream.m: java.io.EOFException
        at com.google.android.gms.ads.exoplayer1.upstream.h.a(:com.google.android.gms.dynamite_dynamitemodulesa@12685026@12.6.85 (040700-197041431):103)
        at com.google.android.gms.ads.exoplayer1.upstream.i.a(:com.google.android.gms.dynamite_dynamitemodulesa@12685026@12.6.85 (040700-197041431):22)
        at com.google.android.gms.ads.internal.video.exoplayer1.w.a(:com.google.android.gms.dynamite_dynamitemodulesa@12685026@12.6.85 (040700-197041431):84)
        at com.google.android.gms.ads.exoplayer1.extractor.b.a(:com.google.android.gms.dynamite_dynamitemodulesa@12685026@12.6.85 (040700-197041431):9)
        at com.google.android.gms.ads.exoplayer1.extractor.mp4.f.a(:com.google.android.gms.dynamite_dynamitemodulesa@12685026@12.6.85 (040700-197041431):16)
        at com.google.android.gms.ads.exoplayer1.upstream.p.run(:com.google.android.gms.dynamite_dynamitemodulesa@12685026@12.6.85 (040700-197041431):23)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

And the error codes:

> 06-27 16:29:08.822 7707-7707/com.google.android.gms.example.rewardedvideoexample W/Ads: ExoPlayer failed during precache: PlayerError Exception: com.google.android.gms.ads.exoplayer1.upstream.m: java.io.EOFException
06-27 16:29:08.945 7707-7839/com.google.android.gms.example.rewardedvideoexample W/Ads: Failed to preload url https://redirector.gvt1.com/api/manifest/hls_variant/requiressl/yes/source/gfp_video_ads/id/4bc67cbb8c201d8e/itag/0/playlist_type/LIVE/acao/yes/mime/application%2Fx-mpegURL/ip/0.0.0.0/ipbits/0/expire/1561642146/sparams/ip,ipbits,expire,requiressl,source,id,itag,playlist_type,acao,mime/signature/6BC13461A7FA842ECB88E8B457EF1678E07B27C0.0908BF1506B03A7A765AE4F4166551388642B6A1/key/ck2/file/index.m3u8 Exception: Abort requested before buffering finished. 
06-27 16:29:09.036 7707-7707/com.google.android.gms.example.rewardedvideoexample W/Ads: Failed to load ad: 0
06-27 16:29:09.046 7707-7707/com.google.android.gms.example.rewardedvideoexample W/Ads: Failed to load ad: 3

Requesting from Turkey

**Comment by huymc** [comment]
It worked fine today. Thank you!
