### ISSUE TITLE
not getting video ads.

### ISSUE THREAD

**Issue by jibraniqbal666** [googleads/googleads-mobile-android-examples#140]
I have just cloned the repository, i am not getting video rewards ads in any app, i have build, or you samples is this a problem of region, i am situated in Pakistan, i am using test app Id and unit Id, other ads are working fine.

Log :
2018-10-10 12:16:05.965 23525-23525/com.google.android.gms.example.rewardedvideoexample I/Ads: Starting ad request.
2018-10-10 12:16:05.965 23525-23525/com.google.android.gms.example.rewardedvideoexample I/Ads: SDK version: afma-sdk-a-v14366015.12451000.1
2018-10-10 12:16:05.965 23525-23525/com.google.android.gms.example.rewardedvideoexample I/Ads: Use AdRequest.Builder.addTestDevice("23C6A7E11A180074D843AB5B8DA0ACBE") to get test ads on this device.
2018-10-10 12:16:09.300 23525-24050/com.google.android.gms.example.rewardedvideoexample W/Ads: Fail to instantiate adapter com.google.DummyAdapter
    android.os.RemoteException
        at com.google.android.gms.internal.ads.zzxm.zzbp(Unknown Source)
        at com.google.android.gms.internal.ads.zzxm.zzbo(Unknown Source)
        at com.google.android.gms.internal.ads.zzxm.zzbm(Unknown Source)
        at com.google.android.gms.internal.ads.zzxo.dispatchTransaction(Unknown Source)
        at com.google.android.gms.internal.ads.zzek.onTransact(Unknown Source)
        at android.os.Binder.transact(Binder.java:499)
        at oa.a(:com.google.android.gms.dynamite_adsdynamite@14366044@14.3.66 (040300-213742215):8)
        at com.google.android.gms.ads.internal.mediation.client.d.a(:com.google.android.gms.dynamite_adsdynamite@14366044@14.3.66 (040300-213742215):4)
        at com.google.android.gms.ads.internal.reward.a.a(:com.google.android.gms.dynamite_adsdynamite@14366044@14.3.66 (040300-213742215):13)
        at com.google.android.gms.ads.internal.reward.mediation.j.d_(:com.google.android.gms.dynamite_adsdynamite@14366044@14.3.66 (040300-213742215):20)
        at com.google.android.gms.ads.internal.util.b.run(:com.google.android.gms.dynamite_adsdynamite@14366044@14.3.66 (040300-213742215):4)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
2018-10-10 12:16:09.300 23525-23525/com.google.android.gms.example.rewardedvideoexample W/Ads: Failed to load ad: 3

**Comment by stowy** [comment]
Hi, thanks for your query.

These github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.
