### ISSUE TITLE
Failed to load ad: 3 with DynamiteModule errror

### ISSUE THREAD

**Issue by tpatikirikorala** [googleads/googleads-mobile-android-examples#146]
I just cloned bannerexample and ran it as is. Banner does not load and there are several exceptions.
How can I fix this? My production app logs the same 'Failed to load ad: 3', the entire app has not made a admob request for 3 months now. 

12-05 16:47:02.060 17567-17588/com.google.android.gms.example.bannerexample I/DynamiteModule: Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:290
12-05 16:47:02.061 17567-17588/com.google.android.gms.example.bannerexample I/DynamiteModule: Selected remote version of com.google.android.gms.ads.dynamite, version >= 290
12-05 16:47:02.069 17567-17587/com.google.android.gms.example.bannerexample W/Ads: Data collection startup failed. No data will be collected.
    com.google.android.gms.dynamite.DynamiteModule$LoadingException: No acceptable module found. Local version is 0 and remote version is 0.
        at com.google.android.gms.dynamite.DynamiteModule.load(Unknown Source)
        at com.google.android.gms.internal.measurement.zzep.zzg(Unknown Source)
        at com.google.android.gms.internal.measurement.zzeq.zzgd(Unknown Source)
        at com.google.android.gms.internal.measurement.zzep$zzb.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)
12-05 16:47:02.070 17567-17587/com.google.android.gms.example.bannerexample W/Ads: Failed to connect to measurement client.
12-05 16:47:02.142 17567-17588/com.google.android.gms.example.bannerexample W/Ads: #007 Could not call remote method. @28
    com.google.android.gms.internal.ads.zzbbg: com.google.android.gms.dynamite.DynamiteModule$LoadingException: Failed to instantiate module class: com.google.android.gms.ads.measurement.DynamiteMeasurementManager
        at com.google.android.gms.internal.ads.zzbbe.zza(Unknown Source)
        at com.google.android.gms.internal.ads.zzakm.zza(Unknown Source)
        at com.google.android.gms.internal.ads.zzakn.run(Unknown Source)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: com.google.android.gms.dynamite.DynamiteModule$LoadingException: Failed to instantiate module class: com.google.android.gms.ads.measurement.DynamiteMeasurementManager
        at com.google.android.gms.dynamite.DynamiteModule.instantiate(Unknown Source)
        at com.google.android.gms.internal.ads.zzbbe.zza(Unknown Source)
        at com.google.android.gms.internal.ads.zzakm.zza(Unknown Source) 
        at com.google.android.gms.internal.ads.zzakn.run(Unknown Source) 
        at java.lang.Thread.run(Thread.java:818) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.ads.measurement.DynamiteMeasurementManager" on path: DexPathList[[zip file "/data/data/com.google.android.gms/app_chimera/m/00000054/DynamiteModulesA_GmsCore_prodlmp_hdpi_release.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
        at ad.loadClass(:com.google.android.gms.dynamite_dynamiteloader@12685007@12.6.85 (020304-197041431):6)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at com.google.android.gms.dynamite.DynamiteModule.instantiate(Unknown Source)
        at com.google.android.gms.internal.ads.zzbbe.zza(Unknown Source) 
        at com.google.android.gms.internal.ads.zzakm.zza(Unknown Source) 
        at com.google.android.gms.internal.ads.zzakn.run(Unknown Source) 
        at java.lang.Thread.run(Thread.java:818) 
    	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.ads.measurement.DynamiteMeasurementManager
        at java.lang.Class.classForName(Native Method)
        at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
        at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
        at ae.loadClass(:com.google.android.gms.dynamite_dynamiteloader@12685007@12.6.85 (020304-197041431):123)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
        		... 7 more
     Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
12-05 16:47:03.054 17567-17627/com.google.android.gms.example.bannerexample W/Ads: Invoke Firebase method getInstance error.
    The Google Mobile Ads SDK will not integrate with Firebase. Admob/Firebase integration requires the latest Firebase SDK jar, but Firebase SDK is either missing or out of date
12-05 16:47:03.093 17567-17567/com.google.android.gms.example.bannerexample I/Ads: Updating ad debug logging enablement.
12-05 16:47:03.149 17567-17567/com.google.android.gms.example.bannerexample I/Ads: Starting ad request.
    SDK version: afma-sdk-a-v14300000.14300000.0
12-05 16:47:03.150 17567-17567/com.google.android.gms.example.bannerexample I/Ads: This request is sent from a test device.
12-05 16:47:03.161 17567-17567/com.google.android.gms.example.bannerexample W/Ads: Not retrying to fetch app settings
12-05 16:47:03.373 17567-17609/com.google.android.gms.example.bannerexample W/Ads: Update ad debug logging enablement as false
12-05 16:47:03.904 17567-17585/com.google.android.gms.example.bannerexample I/Ads: No fill from ad server.
12-05 16:47:03.917 17567-17567/com.google.android.gms.example.bannerexample I/Ads: Scheduling ad refresh 60000 milliseconds from now.
12-05 16:47:03.917 17567-17567/com.google.android.gms.example.bannerexample W/Ads: Failed to load ad: 3

**Comment by stowy** [comment]
Error code 3 [means a no fill](https://developers.google.com/android/reference/com/google/android/gms/ads/AdRequest.html#ERROR_CODE_NO_FILL). This is unrelated to the logs regarding dynamite loading.

This error is advising you that no ad placement was found to match your request. If you were running on a simulator or a whitelisted device, this is not expected since you should receive a test ad. If you were running on a device that is not whitelisted, then it may be expected.

Please let me know if you are still having this issue.

**Comment by kod1r0v** [comment]
> Ошибка код 3 [означает отсутствие заполнения](https://developers.google.com/android/reference/com/google/android/gms/ads/AdRequest.html#ERROR_CODE_NO_FILL). Это не связано с журналами, касающимися загрузки динамита.
> 
> Эта ошибка указывает на то, что ни одно объявление не было найдено в соответствии с вашим запросом. Если вы были запущены на тренажере или в белом устройстве, это не ожидается, так как вы должны получить тестовое объявление. Если вы работали на устройстве, которое не указано в белом списке, то это можно ожидать.
> 
> Пожалуйста, дайте мне знать, если у вас все еще есть этот вопрос.

А как исправить эту ошибку?

**Comment by stowy** [comment]
Hi @kod1r0v , thanks for your query.

A 'no fill' error is not an error with the code, it can be a legitimate error meaning that we were unable to place an ad for your placement. It can also mean however that there is an issue with your ad unit / app and it's not receiving ads. 

For further support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.
