### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion

### ISSUE THREAD

**Issue by shewenbiao** [googleads/googleads-mobile-android-examples#182]
sdk version: 17.2.1
target sdk version: 28
affected device: Android 9.0
```java
java.lang.NoClassDefFoundError: Failed resolution of: Lorg/apache/http/ProtocolVersion;
    at gm.b(:com.google.android.gms.dynamite_adsdynamite@17785077@17.7.85 (100300-253824076):3)
    at gn.a(:com.google.android.gms.dynamite_adsdynamite@17785077@17.7.85 (100300-253824076):3)
    at gp.a(:com.google.android.gms.dynamite_adsdynamite@17785077@17.7.85 (100300-253824076):18)
    at com.google.android.gms.ads.internal.util.aq.a(:com.google.android.gms.dynamite_adsdynamite@17785077@17.7.85 (100300-253824076):5)
    at fq.a(:com.google.android.gms.dynamite_adsdynamite@17785077@17.7.85 (100300-253824076):19)
    at fq.run(:com.google.android.gms.dynamite_adsdynamite@17785077@17.7.85 (100300-253824076):8)
Caused by: java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/00000008/AdsDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/00000008/AdsDynamite.apk!/lib/armeabi-v7a, /data/user_de/0/com.google.android.gms/app_chimera/m/00000008/AdsDynamite.apk!/lib/armeabi, /system/lib, /vendor/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    at ab.loadClass(:com.google.android.gms.dynamite_dynamiteloader@17785077@17.7.85 (100300-253824076):4)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    ... 6 more
java.lang.ClassNotFoundException: Didn't find class "org.apache.http.ProtocolVersion" on path: DexPathList[[zip file "/data/user_de/0/com.google.android.gms/app_chimera/m/00000008/AdsDynamite.apk"],nativeLibraryDirectories=[/data/user_de/0/com.google.android.gms/app_chimera/m/00000008/AdsDynamite.apk!/lib/armeabi-v7a, /data/user_de/0/com.google.android.gms/app_chimera/m/00000008/AdsDynamite.apk!/lib/armeabi, /system/lib, /vendor/lib]]
    at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    at ab.loadClass(:com.google.android.gms.dynamite_dynamiteloader@17785077@17.7.85 (100300-253824076):4)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    at gm.b(:com.google.android.gms.dynamite_adsdynamite@17785077@17.7.85 (100300-253824076):3)
    at gn.a(:com.google.android.gms.dynamite_adsdynamite@17785077@17.7.85 (100300-253824076):3)
    at gp.a(:com.google.android.gms.dynamite_adsdynamite@17785077@17.7.85 (100300-253824076):18)
    at com.google.android.gms.ads.internal.util.aq.a(:com.google.android.gms.dynamite_adsdynamite@17785077@17.7.85 (100300-253824076):5)
    at fq.a(:com.google.android.gms.dynamite_adsdynamite@17785077@17.7.85 (100300-253824076):19)
    at fq.run(:com.google.android.gms.dynamite_adsdynamite@17785077@17.7.85 (100300-253824076):8)
```

**Comment by stowy** [comment]
This has been fixed in the most recent Google play services update.

To resolve for apps that aren't up to date, add `<uses-library android:name="org.apache.http.legacy" android:required="false" />` to your AndroidManifest.xml.
