### ISSUE TITLE
Android Shared Storage protection issue

### ISSUE THREAD

**Issue by girubhai** [googleads/googleads-mobile-android-examples#183]
I had implemented Google Native Ads as given in [Native Ads](https://developers.google.com/admob/android/native/start)

It is working perfect in all devices except Android 4.x version. The crash log in console is

```
Non-fatal Exception: java.lang.IllegalArgumentException: Optimized data directory /storage/emulated/0/Android/data/com.myapp/cache is not owned by the current user. Shared storage cannot protect your application from code injection attacks.
       at dalvik.system.DexFile.(DexFile.java:100)
       at dalvik.system.DexFile.loadDex + 149(DexFile.java:149)
       at dalvik.system.DexPathList.loadDexFile + 251(DexPathList.java:251)
       at dalvik.system.DexPathList.makeDexElements + 219(DexPathList.java:219)
       at dalvik.system.DexPathList.(DexPathList.java:96)
       at dalvik.system.BaseDexClassLoader.(BaseDexClassLoader.java:56)
       at dalvik.system.DexClassLoader.(DexClassLoader.java:57)
       at ir.b + 31(ir.java:31)
       at ir.a + 5(ir.java:5)
       at iu.a + 1(iu.java:1)
       at com.google.android.gms.ads.internal.ag.run + 5(ag.java:5)
       at java.util.concurrent.ThreadPoolExecutor.runWorker + 1080(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run + 573(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run + 856(Thread.java:856)
```

From Above crash it shows as Optimized data directory /storage/emulated/0/Android/data/com.myapp/cache is not owned by the current user. **Shared storage cannot protect your application from code injection attacks**

Please note my app was working good with same NativeAd code before 13th Aug 2019. after that its not working with NativeAd code.

Please help.

**Comment by stowy** [comment]
@girubhai can you please file an issue in the support forum https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help file an issue for this crash.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

**Comment by gpawlik** [comment]
Hi @girubhai , did you manage to solve this issue?
