### ISSUE TITLE
AndroidRuntimeException: requestFeature() must be called before adding content

### ISSUE THREAD

**Issue by Leiluojun** [googleads/googleads-mobile-android-examples#213]
com.google.android.gms.ads.AdActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3190)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3300)
	at android.app.ActivityThread.access$1000(ActivityThread.java:211)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1705)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:145)
	at android.app.ActivityThread.main(ActivityThread.java:6946)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1404)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1199)
Caused by: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
	at com.android.internal.policy.impl.PhoneWindow.requestFeature(PhoneWindow.java:374)
	at android.app.Activity.requestWindowFeature(Activity.java:3934)
	at com.google.android.gms.ads.internal.overlay.k.a(:com.google.android.gms.policy_ads_fdr_dynamite@21207002@21207002.283464268.283464268:24)
	at com.google.android.gms.ads.internal.overlay.client.b.a(:com.google.android.gms.policy_ads_fdr_dynamite@21207002@21207002.283464268.283464268:17)
	at ff.onTransact(:com.google.android.gms.policy_ads_fdr_dynamite@21207002@21207002.283464268.283464268:4)
	at android.os.Binder.transact(Binder.java:380)
	at com.google.android.gms.internal.ads.zzej.transactAndReadExceptionReturnVoid(Unknown Source) (#pluginId:host#)
	at com.google.android.gms.internal.ads.p.onCreate(Unknown Source)
	at com.google.android.gms.ads.AdActivity.onCreate(Unknown Source)
	at android.app.Activity.performCreate(Activity.java:6575)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1134)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3143)
	... 10 more

**Comment by stowy** [comment]
Hi, sorry for the delay, can you please specify how you reproduced this issue? The following info would help:

- Device model
- Android version
- Mobile Ads SDK version
- app
- ad format

If this is not an issue with a sample app, can I request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.
