### ISSUE TITLE
Native Ad Failed to load native ad:3

### ISSUE THREAD

**Issue by janvalji** [googleads/googleads-mobile-android-examples#228]
Even though we use test ad id, we get the error: Failed to load native ad:3 when test our new app. Could you help us to resolve this issue in our app? Test project is working properly but this error happens when I include it in my own project

**Comment by gordonfreemanix** [comment]
The problem is that native ads normally work on your test project, but it isn't appearing when I add the google_services.json file to the project. I recommend you to convey this urgently

**Comment by stowy** [comment]
Hi @gordonfreemanix  So you are getting a [no fill error](https://developers.google.com/android/reference/com/google/android/gms/ads/AdRequest#public-static-final-int-error_code_no_fill). There could be a variety of reasons for this.

Generally these issues are specifically for issues with the sample apps only, as more in depth support for your specific issues is handled by our support team on the forum.

For support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

**Comment by gordonfreemanix** [comment]
Hi, @stowy thanks for answering.. I asked my question on this forum but nobody answered. a statement must be made on this subject. because there are many people who have the same problem on the Reddit and Stackoverflow. There is no problem in test projects. but when we add google_services.json file to the project, it does not show advertisement and gives error: 3 failed.
apply plugin: 'com.google.gms.google-services'

**Comment by stowy** [comment]
@gordonfreemanix ok - the forum is staffed and you will get a response today. They will dig into your issue with you further.

**Comment by gordonfreemanix** [comment]
https://groups.google.com/d/msg/google-admob-ads-sdk/has54P4-UUI/iWFpRiQHBQAJ

It isn't working when I include the project with native ads in firebase.

**Comment by digitalheir** [comment]
I get NO_FILL when I use test ID's for ordinary devices (id added as test device), and on emulators I get INTERNAL_ERROR.

![Screenshot_1598564712](https://user-images.githubusercontent.com/178797/91498192-a0a84000-e8bf-11ea-8853-2747e0b3ab41.png)

**Comment by digitalheir** [comment]
```
2020-08-27 23:45:15.006 6272-6311/com.google.android.gms.example.nativeadvancedexample W/ConnectionTracker: Exception thrown while unbinding
    java.lang.IllegalArgumentException: Service not registered: lm@c53a4a3
        at android.app.LoadedApk.forgetServiceDispatcher(LoadedApk.java:1757)
        at android.app.ContextImpl.unbindService(ContextImpl.java:1874)
        at android.content.ContextWrapper.unbindService(ContextWrapper.java:792)
        at ce.b(:com.google.android.gms.dynamite_measurementdynamite@201817052@20.18.17 (040700-0):1)
        at ce.a(:com.google.android.gms.dynamite_measurementdynamite@201817052@20.18.17 (040700-0):5)
        at ln.A(:com.google.android.gms.dynamite_measurementdynamite@201817052@20.18.17 (040700-0):10)
        at ky.a(:com.google.android.gms.dynamite_measurementdynamite@201817052@20.18.17 (040700-0):3)
        at dy.run(:com.google.android.gms.dynamite_measurementdynamite@201817052@20.18.17 (040700-0):2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at iw.run(:com.google.android.gms.dynamite_measurementdynamite@201817052@20.18.17 (040700-0):15)
2020-08-27 23:48:11.592 6272-6272/com.google.android.gms.example.nativeadvancedexample I/Ads: This request is sent from a test device.
2020-08-27 23:48:11.611 6272-6445/com.google.android.gms.example.nativeadvancedexample I/Ads: Ad failed to load : 0
```

**Comment by janvalji** [comment]
@stowy Hello, I have a request from you. can you please delete this issue completely? (I don't want to close it, I want it to be deleted completely) thanks

**Comment by janvalji** [comment]
@stowy Hello, I have a request from you. Can you please delete this issue completely? (I don't want to close it, I want it to be deleted completely) Thanks

**Comment by janvalji** [comment]
@stowy I tried everything to reach you. It is a very urgent and very important situation for me. Please delete this issue now. @stowy  @stowy @stowy  @stowy @stowy  @stowy
