### ISSUE TITLE
Application Crashing if no version metadata

### ISSUE THREAD

**Issue by MrcSnm** [googleads/googleads-mobile-android-examples#249]
I can't seem to start my application w/o this line:
<meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />, it always crashes

Even after copying from the tests I can't run it, if I keep this line, I can even call interstitial.isLoaded() and it returns true (from the ad EventListener), trying to show it, however does anything
Even if I call it from runOnUiThread

And the line is present on my app manifest:
<meta-data
          android:name="com.google.android.gms.APPLICATION_ID"
          android:value="ca-app-pub-5208740926566469~6926143142"/>

It causes that error:
```
E/AndroidRuntime: FATAL EXCEPTION: SDLActivity
    Process: com.hipreme.industrialflyingcreature.embed, PID: 24116
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.hipreme.industrialflyingcreature.embed/org.love2d.android.GameActivity}: java.lang.IllegalStateException: A required meta-data tag in your app's AndroidManifest.xml does not exist.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2946)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
     Caused by: java.lang.IllegalStateException: A required meta-data tag in your app's AndroidManifest.xml does not exist.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
        at com.google.android.gms.common.GooglePlayServicesUtilLight.isGooglePlayServicesAvailable(Unknown Source:17)
        at com.google.android.gms.common.GoogleApiAvailabilityLight.isGooglePlayServicesAvailable(Unknown Source:5)
        at com.google.android.gms.internal.ads.zzbaq.zzd(com.google.android.gms:play-services-ads-lite@@19.2.0:67)
        at com.google.android.gms.internal.ads.zzwd.zzd(com.google.android.gms:play-services-ads-lite@@19.2.0:35)
        at com.google.android.gms.internal.ads.zzyt.zzg(com.google.android.gms:play-services-ads-lite@@19.2.0:160)
        at com.google.android.gms.internal.ads.zzyt.zza(com.google.android.gms:play-services-ads-lite@@19.2.0:18)
        at com.google.android.gms.ads.MobileAds.initialize(com.google.android.gms:play-services-ads-lite@@19.2.0:10)
        at org.love2d.android.AdPlayer.<init>(AdPlayer.java:36)
        at org.love2d.android.GameActivity.onCreate(GameActivity.java:158)
        at android.app.Activity.performCreate(Activity.java:7224)
        at android.app.Activity.performCreate(Activity.java:7213)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1272)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2926)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3081) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1831) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:201) 
        at android.app.ActivityThread.main(ActivityThread.java:6810) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873) 
```

**Comment by MrcSnm** [comment]
After trying those lines of code
```java
            ApplicationInfo f = context.getPackageManager().getApplicationInfo(context.getPackageName(), PackageManager.GET_META_DATA);
            Bundle bundle = f.metaData;
            System.out.println(bundle.getString("com.google.android.gms.APPLICATION_ID"));
```
My application crashed too, saying `Attempt to invoke virtual method 'java.lang.String android.os.Bundle.getString(java.lang.String)' on a null object reference`
For some reason it is returning null, would it be something related for being a ndk-based project?
