### ISSUE TITLE
Error: NameNotFoundException: com.google.android.webview when i create a new InterstitialAd

### ISSUE THREAD

**Issue by DoaiNguyen** [googleads/googleads-mobile-android-examples#25]
Caused by android.util.AndroidRuntimeException: android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
       at android.webkit.WebViewFactory.getFactoryClass(WebViewFactory.java:161)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:101)
       at android.webkit.CookieManager.getInstance(CookieManager.java:46)
       at atl.b(:com.google.android.gms.DynamiteModulesA:487)
       at po.a(:com.google.android.gms.DynamiteModulesA:541)
       at po.a(:com.google.android.gms.DynamiteModulesA:144)
       at qn.a(:com.google.android.gms.DynamiteModulesA:150)
       at pm.a(:com.google.android.gms.DynamiteModulesA:312)
       at ul.onTransact(:com.google.android.gms.DynamiteModulesA:81)
       at android.os.Binder.transact(Binder.java:380)
       at com.google.android.gms.ads.internal.client.zzu$zza$zza.com.google.android.gms.dynamic.zzd zzbh()(Unknown Source)
                                                                 boolean zzb(com.google.android.gms.ads.internal.client.AdRequestParcel)
                                                                 void zza(com.google.android.gms.ads.internal.client.zzq)
                                                                 void zza(com.google.android.gms.ads.internal.client.zzw)
                                                                 void zza(com.google.android.gms.ads.internal.client.AdSizeParcel)
                                                                 void zza(com.google.android.gms.internal.zzhh)
                                                                 void zza(com.google.android.gms.internal.zzhl,java.lang.String)
                                                                 void zza(com.google.android.gms.internal.zzdg)
                                                                 void zza(com.google.android.gms.ads.internal.client.zzp)
                                                                 void zza(com.google.android.gms.ads.internal.client.zzy)
                                                                 void setManualImpressionsEnabled(boolean)
                                                                 void zza(com.google.android.gms.ads.internal.reward.client.zzd)
                                                                 void setUserId(java.lang.String)
                                                                 void zza(com.google.android.gms.ads.internal.client.VideoOptionsParcel)
       at com.google.android.gms.ads.internal.client.zzaf.boolean isLoaded()(Unknown Source)
                                                          void zza(com.google.android.gms.ads.internal.client.zzad)
                                                          void setAdListener(com.google.android.gms.ads.AdListener)
                                                          void zza(com.google.android.gms.ads.internal.client.zza)
                                                          void setAdUnitId(java.lang.String)
                                                          void setRewardedVideoAdListener(com.google.android.gms.ads.reward.RewardedVideoAdListener)
                                                          void zzc(boolean)
       at com.google.android.gms.ads.InterstitialAd.boolean isLoaded()(Unknown Source)
                                                    void loadAd(com.google.android.gms.ads.AdRequest)
                                                    void setAdListener(com.google.android.gms.ads.AdListener)
                                                    void setAdUnitId(java.lang.String)
                                                    void setRewardedVideoAdListener(com.google.android.gms.ads.reward.RewardedVideoAdListener)
                                                    void zzc(boolean)

**Comment by DoaiNguyen** [comment]
Fatal Exception: java.lang.NullPointerException
       at android.os.Parcel.readException(Parcel.java:1471)
       at android.os.Parcel.readException(Parcel.java:1419)
       at android.media.IAudioService$Stub$Proxy.getStreamVolume(IAudioService.java:1166)
       at android.media.AudioManager.getStreamVolume(AudioManager.java:773)
       at avu.e(:com.google.android.gms.DynamiteModulesA:20116)
       at avt.e(:com.google.android.gms.DynamiteModulesA:150)
       at alk.a(:com.google.android.gms.DynamiteModulesA:127)
       at alw.a(:com.google.android.gms.DynamiteModulesA:102)
       at alk.a(:com.google.android.gms.DynamiteModulesA:92)
       at avl.e(:com.google.android.gms.DynamiteModulesA:428)
       at avl.onPageFinished(:com.google.android.gms.DynamiteModulesA:387)
       at com.android.webview.chromium.WebViewContentsClientAdapter.onPageFinished(WebViewContentsClientAdapter.java:456)
       at com.android.org.chromium.android_webview.AwContentsClient$AwWebContentsObserver$1.run(AwContentsClient.java:73)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5372)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:970)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:786)
       at dalvik.system.NativeStart.main(NativeStart.java)

**Comment by DoaiNguyen** [comment]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Set android.net.Uri.getQueryParameterNames()' on a null object reference
       at ate.a(:com.google.android.gms.DynamiteModulesA:336)
       at asx.a(:com.google.android.gms.DynamiteModulesA:561)
       at avl.a(:com.google.android.gms.DynamiteModulesA:829)
       at awb.run(:com.google.android.gms.DynamiteModulesA:45)
       at android.os.Handler.handleCallback(Handler.java:815)
       at android.os.Handler.dispatchMessage(Handler.java:104)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5637)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:960)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by clockbyte** [comment]
So what? :) What is that man?
