### ISSUE TITLE
Activity leaking window in native ads

### ISSUE THREAD

**Issue by maxakash** [googleads/googleads-mobile-android-examples#325]
I have implemented native ads from the given example code but I am getting the following error when closing the app.

```
2021-04-07 20:41:15.518 9223-9223/com.whileloop.teestnativeaderror E/WindowManager: android.view.WindowLeaked: Activity com.whileloop.teestnativeaderror.MainActivity has leaked window com.google.android.gms.internal.ads.zzbft{b211038 I.E...... ......I. 0,0-840,0} that was originally added here
        at android.view.ViewRootImpl.<init>(ViewRootImpl.java:598)
        at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:377)
        at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:96)
        at com.google.android.gms.internal.ads.zzcen.zzh(com.google.android.gms:play-services-ads@@19.8.0:53)
        at com.google.android.gms.internal.ads.zzcdf.zzb(com.google.android.gms:play-services-ads@@19.8.0:134)
        at com.google.android.gms.internal.ads.zzcel.onGlobalLayout(com.google.android.gms:play-services-ads@@19.8.0:108)
        at com.google.android.gms.internal.ads.zzbbl.onGlobalLayout(com.google.android.gms:play-services-ads@@19.8.0:6)
        at android.view.ViewTreeObserver.dispatchOnGlobalLayout(ViewTreeObserver.java:1056)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2629)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1722)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7621)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1029)
        at android.view.Choreographer.doCallbacks(Choreographer.java:852)
        at android.view.Choreographer.doFrame(Choreographer.java:787)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1014)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:235)
        at android.app.ActivityThread.main(ActivityThread.java:7441)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)


```

I have even tried implementing the exact code given in the example in new project but still I am always getting the same error on exiting the activity.

**Comment by Humanbeing-bit** [comment]
i am also facing the same problem any idea how to solve the issue?
