### ISSUE TITLE
Issue when targetting android 12 sdk 31

### ISSUE THREAD

**Issue by JimmyMantilla** [googleads/googleads-mobile-android-examples#376]
Hello, when i add the dependencie of admob (implementation 'com.google.android.gms:play-services-ads:20.2.0) after updating to targetsdkversion=31 (im ussing a google pixel with android 12) the app crash in the beggining, in logcat it says this error
E/AndroidRuntime: FATAL EXCEPTION: pool-3-thread-1
    Process: com.package.myapp, PID: 2134
    java.lang.IllegalArgumentException: com.package.myapp: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:174)
        at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:108)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:86)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:75)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)

i just have a hello world activity, no code, anything, i tested it in a new project i dont have any other library just created a new project and then add the admob sdk and after that it crashes in the begining, please i hope that someone from google support could help me

**Comment by Sanikakumari** [comment]
Help

**Comment by Kumar-Abhijeet-Jha** [comment]
//for android 12 implement this library if you are dealing with pending intent
   
implementation 'androidx.work:work-runtime:2.7.1'

**Comment by malandr2** [comment]
Marking as obsolete.
