### ISSUE TITLE
Error Using Ads with Jetpack Compose

### ISSUE THREAD

**Issue by tetrium** [googleads/googleads-mobile-android-examples#382]
Hi, i have a issue , when I implement the library: 

    implementation 'com.google.android.gms:play-services-ads:20.3.0'

I am getting this message when I try to execute the app:

 java.lang.IllegalArgumentException: com.hardcodeflow.futurereadertarot: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
    Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
        at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
        at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
        at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
        at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:174)
        at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:108)
        at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:86)
        at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:75)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)

When I remove the line " implementation 'com.google.android.gms:play-services-ads:20.3.0'"
  from the Gradle is working fine , can you help me?

**Comment by hau99** [comment]
> Hi, i have a issue , when I implement the library: 
> 
>     implementation 'com.google.android.gms:play-services-ads:20.3.0'
> 
> I am getting this message when I try to execute the app:
> 
>  java.lang.IllegalArgumentException: com.hardcodeflow.futurereadertarot: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
>     Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
>         at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
>         at android.app.PendingIntent.getBroadcastAsUser(PendingIntent.java:645)
>         at android.app.PendingIntent.getBroadcast(PendingIntent.java:632)
>         at androidx.work.impl.utils.ForceStopRunnable.getPendingIntent(ForceStopRunnable.java:174)
>         at androidx.work.impl.utils.ForceStopRunnable.isForceStopped(ForceStopRunnable.java:108)
>         at androidx.work.impl.utils.ForceStopRunnable.run(ForceStopRunnable.java:86)
>         at androidx.work.impl.utils.SerialExecutor$Task.run(SerialExecutor.java:75)
>         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
>         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
>         at java.lang.Thread.run(Thread.java:920)
> 
> 
> When I remove the line " implementation 'com.google.android.gms:play-services-ads:20.3.0'"
>   from the Gradle is working fine , can you help me?
> 
>
