### ISSUE TITLE
java.lang.RuntimeException android.hardware.display.DisplayManagerGlobal.getDisplayInfo

### ISSUE THREAD

**Issue by klvnmarshall** [googleads/googleads-mobile-android-examples#407]
**Crash**

Huawei Y6 Pro 2019
Android 9 (SDK 28)

AdMob SDK 20.5.0

```
java.lang.RuntimeException: 	at android.hardware.display.DisplayManagerGlobal.getDisplayInfo(DisplayManagerGlobal.java:151)
	at android.hardware.display.DisplayManagerGlobal.getCompatibleDisplay(DisplayManagerGlobal.java:210)
	at android.app.ResourcesManager.getAdjustedDisplay(ResourcesManager.java:330)
	at android.app.ContextImpl.getDisplay(ContextImpl.java:2478)
	at android.view.WindowManagerImpl.getDefaultDisplay(WindowManagerImpl.java:233)
	at com.google.android.gms.ads.omid.library.utils.a.i(:com.google.android.gms.policy_ads_fdr_dynamite@214106404@214106404057.409717972.409717972:2)
	at com.google.android.gms.ads.omid.library.walking.e.run(:com.google.android.gms.policy_ads_fdr_dynamite@214106404@214106404057.409717972.409717972:28)
  at android.os.Handler.handleCallback (Handler.java:907)
  at android.os.Handler.dispatchMessage (Handler.java:105)
  at android.os.Looper.loop (Looper.java:216)
  at android.app.ActivityThread.main (ActivityThread.java:7625)
  at java.lang.reflect.Method.invoke (Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:524)
  at com.android.internal.os.ZygoteInit.main (ZygoteInit.java:987)

```

**Comment by JillSong** [comment]
We no longer support ads sdk 20.5.0. Closing as obsolete.
