### ISSUE TITLE
java.lang.IllegalStateException: Activity top position already set to onTop=false

### ISSUE THREAD

**Issue by YouCii** [googleads/googleads-mobile-android-examples#423]
We found a lot of crashes in our app with the following stack:
```
java.lang.IllegalStateException: Activity top position already set to onTop=false
	at android.app.ActivityThread.handleTopResumedActivityChanged(ActivityThread.java:4730)
	at android.app.servertransaction.TopResumedActivityChangeItem.execute(TopResumedActivityChangeItem.java:39)
	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2216)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loop(Looper.java:237)
	at android.app.ActivityThread.main(ActivityThread.java:7948)
	at java.lang.reflect.Method.invoke(Method.java)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1075)
```

And the Activity-Stack is as follows:
```
2022-03-29 11:44:55 : com.google.android.gms.ads.AdActivity onCreate
2022-03-29 11:44:55 : com.google.android.gms.ads.AdActivity onStart
2022-03-29 11:44:55 : com.google.android.gms.ads.AdActivity onResume
```

The sdk-version is 
<img width="476" alt="image" src="https://user-images.githubusercontent.com/17899073/161220781-1e158358-0100-4738-a691-c190f97f780b.png">

**Comment by YouCii** [comment]
Can someone reply？

**Comment by superroye** [comment]
> 

many

**Comment by malandr2** [comment]
Hi @superroye, the stack itself doesn't point to `gms.ads` in the stack trace. Update to the latest GMA SDK. If you're still experiencing the crash reach out to https://support.google.com/admob/contact/contact_us_gma_sdk to help troubleshoot
