### ISSUE TITLE
App Crashes when using Admob-Facebook Mediation

### ISSUE THREAD

**Issue by shahzad1** [googleads/googleads-mobile-android-examples#437]
Hi, I'm trying to add Admob-Facebook mediation but my app is crashing after adding the **mediation** dependency:
`
implementation 'com.google.android.gms:play-services-ads:20.6.0'
implementation 'com.google.ads.mediation:facebook:6.10.0.0'
`

### **Below is complete crash log**
`
java.lang.NoSuchMethodError: No virtual method getActivityStack()Ljava/util/Deque; in class Lcom/facebook/ads/internal/util/common/ANActivityLifecycleCallbacksListener; or its super classes (declaration of 'com.facebook.ads.internal.util.common.ANActivityLifecycleCallbacksListener' appears in /data/app/~~Ypqzh_WrUR_nDzWiXapB3w==/com.example.packagename--cSZzKrp3fgTe49KoFIWyg==/base.apk)
        at com.facebook.ads.redexgen.X.J9.D(:31925)
        at com.facebook.ads.redexgen.X.FV.Q(:26102)
        at com.facebook.ads.redexgen.X.FV.L(:26033)
        at com.facebook.ads.redexgen.X.8A.onContentProviderCreated(:18085)
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.doCallInitialize(DynamicLoaderFactory.java:159)
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory.access$200(DynamicLoaderFactory.java:41)
        at com.facebook.ads.internal.dynamicloading.DynamicLoaderFactory$1.run(DynamicLoaderFactory.java:121)
        at java.lang.Thread.run(Thread.java:923)

`

**Comment by shahzad1** [comment]
Wake up, guys.

**Comment by ericleich** [comment]
Closing this issue because it is not an issue with the Android samples.

For mediation issues [googleads-mobile-android-mediation](https://github.com/googleads/googleads-mobile-android-mediation) would be the more appropriate place to report this, but I can already tell you from the stack trace that the Facebook adapter binary isn’t in the trace, and so you won’t get much help there for this particular issue. This is a Facebook Audience Network SDK crash and I recommend reaching out to Facebook support.
