### ISSUE TITLE
Crash on NativeContentAdView

### ISSUE THREAD

**Issue by ashwini009** [googleads/googleads-mobile-android-examples#45]
I am using Google DFP ads for showing ads on our app. The Crashlytics has reported almost 30 crashes reported. Here is the stack trace. Any help will be highly appreciated.
```
Fatal Exception: android.view.InflateException: Binary XML file line #3: Error inflating class com.google.android.gms.ads.formats.NativeContentAdView
       at android.view.LayoutInflater.createView(LayoutInflater.java:633)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:892)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at com.aranoah.healthkart.plus.home.banner.BannerFragment.onCreateView(BannerFragment.java:74)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2074)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
       at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1632)
       at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:637)
       at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:166)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1237)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1085)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1611)
       at com.aranoah.healthkart.plus.utils.WrapContentHeightViewPager.onMeasure(WrapContentHeightViewPager.java:35)
       at android.view.View.measure(View.java:17764)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5620)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1687)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:755)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:624)
       at android.view.View.measure(View.java:17764)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5620)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:454)
       at android.view.View.measure(View.java:17764)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5620)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1687)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:755)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:624)
       at android.view.View.measure(View.java:17764)
       at android.support.v4.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1415)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:454)
       at android.support.v4.widget.NestedScrollView.onMeasure(NestedScrollView.java:480)
       at android.view.View.measure(View.java:17764)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5620)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:671)
       at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:90)
       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1319)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:736)
       at android.view.View.measure(View.java:17764)
       at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1079)
       at android.view.View.measure(View.java:17764)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5620)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:454)
       at android.view.View.measure(View.java:17764)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5620)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:454)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
       at android.view.View.measure(View.java:17764)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5620)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1687)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:755)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:624)
       at android.view.View.measure(View.java:17764)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5620)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:454)
       at android.view.View.measure(View.java:17764)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5620)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1687)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:755)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:624)
       at android.view.View.measure(View.java:17764)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5620)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:454)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2734)
       at android.view.View.measure(View.java:17764)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2349)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1373)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1597)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1251)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6438)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:795)
       at android.view.Choreographer.doCallbacks(Choreographer.java:598)
       at android.view.Choreographer.doFrame(Choreographer.java:567)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:781)
       at android.os.Handler.handleCallback(Handler.java:810)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:189)
       at android.app.ActivityThread.main(ActivityThread.java:5532)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:892)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at com.aranoah.healthkart.plus.home.banner.BannerFragment.onCreateView(BannerFragment.java:74)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2074)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
       at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1632)
       at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:637)
       at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:166)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1237)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1085)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1611)
       at com.aranoah.healthkart.plus.utils.WrapContentHeightViewPager.onMeasure(WrapContentHeightViewPager.java:35)
       at android.view.View.measure(View.java:17764)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5620)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1687)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:755)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:624)
       at android.view.View.measure(View.java:17764)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5620)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:454)
       at android.view.View.measure(View.java:17764)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5620)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1687)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:755)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:624)
       at android.view.View.measure(View.java:17764)
       at android.support.v4.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1415)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:454)
       at android.support.v4.widget.NestedScrollView.onMeasure(NestedScrollView.java:480)
       at android.view.View.measure(View.java:17764)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5620)
       at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:671)
       at android.support.design.widget.HeaderScrollingViewBehavior.onMeasureChild(HeaderScrollingViewBehavior.java:90)
       at android.support.design.widget.AppBarLayout$ScrollingViewBehavior.onMeasureChild(AppBarLayout.java:1319)
       at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:736)
       at android.view.View.measure(View.java:17764)
       at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1079)
       at android.view.View.measure(View.java:17764)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5620)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:454)
       at android.view.View.measure(View.java:17764)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5620)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:454)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
       at android.view.View.measure(View.java:17764)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5620)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1687)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:755)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:624)
       at android.view.View.measure(View.java:17764)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5620)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:454)
       at android.view.View.measure(View.java:17764)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5620)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1687)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:755)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:624)
       at android.view.View.measure(View.java:17764)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5620)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:454)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2734)
       at android.view.View.measure(View.java:17764)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2349)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1373)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1597)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1251)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6438)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:795)
       at android.view.Choreographer.doCallbacks(Choreographer.java:598)
       at android.view.Choreographer.doFrame(Choreographer.java:567)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:781)
       at android.os.Handler.handleCallback(Handler.java:810)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:189)
       at android.app.ActivityThread.main(ActivityThread.java:5532)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:950)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:745)
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Boolean kik.a(java.lang.String, java.lang.Boolean)' on a null object reference
       at kie.a(:com.google.android.gms:1227)
       at kid.b(:com.google.android.gms:197)
       at iyk.logEvent(:com.google.android.gms:1216)
       at iyk.logEvent(:com.google.android.gms:60)
       at com.google.android.chimera.container.DebugLogger.logEvent(:com.google.android.gms:65)
       at com.google.android.chimera.container.ConfigurationManager.loadModuleByModuleId(:com.google.android.gms:546)
       at iym.a(:com.google.android.gms:74)
       at cuo.<init>(:com.google.android.gms:1112)
       at cuo.a(:com.google.android.gms:27)
       at com.google.android.gms.ads.NativeAdViewDelegateCreatorImpl.newNativeAdViewDelegate(:com.google.android.gms:41)
       at com.google.android.gms.ads.internal.formats.client.i.onTransact(:com.google.android.gms:59)
       at android.os.Binder.transact(Binder.java:380)
       at com.google.android.gms.internal.zzej$zza$zza.zza(Unknown Source)
       at com.google.android.gms.internal.zzeu.zzb(Unknown Source)
       at com.google.android.gms.ads.internal.client.zzl$6.zzkk(Unknown Source)
       at com.google.android.gms.ads.internal.client.zzl$6.zzkh(Unknown Source)
       at com.google.android.gms.ads.internal.client.zzl$zza.zzkp(Unknown Source)
       at com.google.android.gms.ads.internal.client.zzl.zza(Unknown Source)
       at com.google.android.gms.ads.internal.client.zzl.zza(Unknown Source)
       at com.google.android.gms.ads.formats.NativeAdView.zzdz(Unknown Source)
       at com.google.android.gms.ads.formats.NativeAdView.<init>(Unknown Source)
       at com.google.android.gms.ads.formats.NativeContentAdView.<init>(Unknown Source)
       at java.lang.reflect.Constructor.newInstance(Constructor.java)
       at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
       at android.view.LayoutInflater.createView(LayoutInflater.java:607)
       at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
       at android.view.LayoutInflater.parseInclude(LayoutInflater.java:892)
       at android.view.LayoutInflater.rInflate(LayoutInflater.java:802)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
       at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
       at com.aranoah.healthkart.plus.home.banner.BannerFragment.onCreateView(BannerFragment.java:74)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2074)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1104)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
       at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:758)
       at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1632)
       at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:637)
       at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:166)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1237)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1085)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1611)
       at 
```

**Comment by temrich** [comment]
Hi, 
Thank you for contacting us. The GitHub issue tracker is for questions and feature requests for our Android sample apps. If you are running into an issue with our SDK, please reach out to us through the Google Mobile Ads Developer forum (https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android).
