### ISSUE TITLE
ANR when MobileAds.initialize

### ISSUE THREAD

**Issue by yanxiong-github** [googleads/googleads-mobile-android-examples#452]
We have a lot of ANR reports in google play console
Call MobileAds. Initialize when the activity starts，Anr log as follows：
【ANR log】
Subject: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 10.  Wait queue head age: 15067.0ms.)
Build: TECNO/LC7-GL/TECNO-LC7:10/QP1A.190711.020/BCF-GL-200612V304:user/release-keys

nullAndroid time :[2022-07-01 02:51:12.89] [17765044.000]
CPU usage from 183689ms to 0ms ago (2022-07-01 02:48:03.417 to 2022-07-01 02:51:07.105):
  14% 11500/system_server: 8.3% user + 5.9% kernel / faults: 101851 minor
  4.9% 527/surfaceflinger: 2.6% user + 2.2% kernel / faults: 543 minor
  3.9% 491/android.hardware.graphics.composer@2.1-service: 1.7% user + 2.1% kernel / faults: 33237 minor
  2.5% 575/adbd: 0.4% user + 2% kernel / faults: 22013 minor
  1.9% 11690/com.android.systemui: 1.4% user + 0.5% kernel / faults: 4286 minor
  1.1% 12669/com.transsion.smartpanel: 0.9% user + 0.2% kernel / faults: 18101 minor
  0.9% 620/res_monitor: 0.2% user + 0.7% kernel
  0.7% 349/logd: 0.2% user + 0.5% kernel / faults: 153 minor
  0.6% 15197/com.transsion.phonemaster: 0.6% user + 0% kernel / faults: 275 minor
  0.6% 632/vendor.mediatek.hardware.pq@2.2-service: 0.2% user + 0.4% kernel
  0.5% 15306/kworker/u8:0: 0% user + 0.5% kernel
  0.6% 11603/kworker/u8:17: 0% user + 0.6% kernel
  0.5% 11604/kworker/u8:18: 0% user + 0.5% kernel
  0.5% 2014/pnpmgr: 0% user + 0.5% kernel
  0.4% 11595/kworker/u8:9: 0% user + 0.4% kernel
  0.4% 15499/logcat: 0.2% user + 0.2% kernel / faults: 8 minor
  0.3% 225/resource_monito: 0% user + 0.3% kernel
  0.3% 506/vendor.mediatek.hardware.mtkpower@1.0-service: 0% user + 0.2% kernel / faults: 2 minor
  0.3% 5097/hif_thread: 0% user + 0.3% kernel
  0.3% 180/pbm: 0% user + 0.3% kernel
  0.3% 5096/main_thread: 0% user + 0.3% kernel
  0.2% 12169/com.transsion.trancare: 0.1% user + 0.1% kernel / faults: 1402 minor
  0.2% 5099/rx_thread: 0% user + 0.2% kernel
  0.2% 520/lmkd: 0% user + 0.2% kernel
  0.2% 14880/com.facebook.appmanager: 0.1% user + 0.1% kernel / faults: 550 minor
  0.2% 15389/kworker/1:0: 0% user + 0.2% kernel / faults: 671 minor
  0.2% 11354/netd: 0% user + 0.1% kernel / faults: 899 minor
  0.2% 15556/kworker/3:0: 0% user + 0.2% kernel / faults: 419 minor
  0.2% 12733/autotest.com.update: 0.1% user + 0% kernel / faults: 1993 minor
  0.2% 15588/kworker/u8:1: 0% user + 0.2% kernel
  0.1% 15325/kworker/2:2: 0% user + 0.1% kernel / faults: 473 minor
  0.1% 12518/com.hoffnung.mobile.service: 0.1% user + 0% kernel / faults: 1017 minor
  0.1% 7/rcu_preempt: 0% user + 0.1% kernel
  0.1% 11817/com.android.phone: 0% user + 0% kernel / faults: 261 minor
  0.1% 259/ipi_cpu_dvfs_rt: 0% user + 0.1% kernel
  0% 90/ion_mm_heap: 0% user + 0% kernel
  0.1% 286/exe_cq/0: 0% user + 0.1% kernel
  0.1% 257/present_fence_w: 0% user + 0.1% kernel
  0.1% 605/android.hardware.sensors@2.0-service-mediatek: 0% user + 0% kernel
  0.1% 255/disp_delay_trig: 0% user + 0.1% kernel
  0.1% 350/servicemanager: 0% user + 0% kernel
  0.1% 494/android.hardware.memtrack@1.0-service: 0% user + 0% kernel / faults: 1 minor
  0% 1/init: 0% user + 0% kernel
  0% 600/statsd: 0% user + 0% kernel / faults: 1 minor
  0% 15642/com.google.android.permissioncontroller: 0% user + 0% kernel / faults: 501 minor
  0% 14428/com.transsion.plat.appupdate: 0% user + 0% kernel / faults: 578 minor
  0% 490/android.hardware.graphics.allocator@2.0-service: 0% user + 0% kernel
  0% 11985/com.google.android.ext.services: 0% user + 0% kernel / faults: 746 minor
  0% 250/disp_idlemgr: 0% user + 0% kernel
  0% 266/pvr_defer_free: 0% user + 0% kernel
  0% 288/mmcqd/0: 0% user + 0% kernel
  0% 189/chre_kthread: 0% user + 0% kernel
  0% 512/ashmemd: 0% user + 0% kernel
  0% 278/charger_thread: 0% user + 0% kernel
  0% 11350/audioserver: 0% user + 0% kernel / faults: 8 minor
  0% 11883/com.android.quickstep: 0% user + 0% kernel / faults: 330 minor
  0% 2007/iomanager: 0% user + 0% kernel
  0% 11349/zygote: 0% user + 0% kernel / faults: 509 minor
  0% 418/android.system.suspend@1.0-service: 0% user + 0% kernel
  0% 609/thermal: 0% user + 0% kernel
  0% 12657/com.transsion.hilauncher: 0% user + 0% kernel / faults: 320 minor
  0% 12716/com.google.android.projection.gearhead:shared: 0% user + 0% kernel / faults: 366 minor
  0% 13096/com.transsion.powercenter:pms: 0% user + 0% kernel / faults: 136 minor
  0% 86/dlpt_notify_thr: 0% user + 0% kernel
  0% 1016/mtkfusionrild: 0% user + 0% kernel
  0% 11355/wificond: 0% user + 0% kernel / faults: 49 minor
  0% 14671/com.transsion.plat.appupdate.ui: 0% user + 0% kernel / faults: 59 minor
  0% 15103/com.google.android.setupwizard: 0% user + 0% kernel / faults: 52 minor
  0% 15798/com.google.android.packageinstaller: 0% user + 0% kernel / faults: 192 minor
  0% 351/hwservicemanager: 0% user + 0% kernel / faults: 14 minor
  0% 577/mnld: 0% user + 0% kernel
  0% 12503/com.google.process.gservices: 0% user + 0% kernel / faults: 70 minor
  0% 12531/com.transsion.statisticalsales: 0% user + 0% kernel / faults: 78 minor
  0% 12592/com.transsion.camera: 0% user + 0% kernel / faults: 55 minor
  0% 14459/com.google.android.apps.messaging: 0% user + 0% kernel / faults: 54 minor
  0% 14780/com.android.settings: 0% user + 0% kernel / faults: 61 minor
  0% 14999/com.android.keychain: 0% user + 0% kernel / faults: 77 minor
  0% 15239/com.transsion.phonemanager: 0% user + 0% kernel / faults: 66 minor
  0% 15326/com.google.android.configupdater: 0% user + 0% kernel / faults: 68 minor
  0% 15763/com.android.statementservice: 0% user + 0% kernel / faults: 184 minor
  0% 6/ksoftirqd/0: 0% user + 0% kernel
  0% 15/ksoftirqd/1: 0% user + 0% kernel
  0% 25/ksoftirqd/3: 0% user + 0% kernel
  0% 531/fuelgauged: 0% user + 0% kernel
  0% 11675/android.hardware.wifi@1.0-service-lazy-mediatek: 0% user + 0% kernel
  0% 11753/se.dirac.acs: 0% user + 0% kernel / faults: 22 minor
  0% 11801/com.mediatek.security.service: 0% user + 0% kernel / faults: 201 minor
  0% 12310/com.mediatek.ims: 0% user + 0% kernel / faults: 43 minor
  0% 12620/com.android.se: 0% user + 0% kernel / faults: 67 minor
  0% 12640/com.transsion.batterylab: 0% user + 0% kernel / faults: 60 minor
  0% 14718/com.android.cellbroadcastreceiver: 0% user + 0% kernel / faults: 64 minor
  0% 15139/com.transsion.powercenter: 0% user + 0% kernel / faults: 53 minor
  0% 20/ksoftirqd/2: 0% user + 0% kernel
  0% 97/ion_history: 0% user + 0% kernel
  0% 447/apexd: 0% user + 0% kernel
  0% 946/gsm0710muxd: 0% user + 0% kernel
  0% 11352/cameraserver: 0% user + 0% kernel / faults: 17 minor
  0% 15350/kworker/0:0: 0% user + 0% kernel / faults: 58 minor
  0% 10/migration/0: 0% user + 0% kernel
  0% 14/migration/1: 0% user + 0% kernel
  0% 19/migration/2: 0% user + 0% kernel
  0% 24/migration/3: 0% user + 0% kernel
  0% 184/btif_rxd: 0% user + 0% kernel
  0% 198/ccci_poll1: 0% user + 0% kernel
  0% 216/krtatm: 0% user + 0% kernel
  0% 236/battery_thread: 0% user + 0% kernel
  0% 268/pvr_cacheop: 0% user + 0% kernel
  0% 281/wdtk-0: 0% user + 0% kernel
  0% 296/kworker/1:1H: 0% user + 0% kernel
  0% 339/ueventd: 0% user + 0% kernel
  0% 358/kauditd: 0% user + 0% kernel
  0% 383/jbd2/mmcblk0p38: 0% user + 0% kernel
  0% 417/bringup_monitor: 0% user + 0% kernel
  0% 667/android.hardware.biometrics.fingerprint@2.1-service: 0% user + 0% kernel
  0% 5110/wpa_supplicant: 0% user + 0% kernel
  0% 12206/kworker/u9:1: 0% user + 0% kernel
  0% 15193/kworker/0:1: 0% user + 0% kernel
 +0% 15926/kworker/0:2: 0% user + 0% kernel
 +0% 16013/android.process.media: 0% user + 0% kernel
 +0% 16209/tv.panda.test.monkey: 0% user + 0% kernel
 +0% 16313/com.afmobi.boomplayer: 0% user + 0% kernel
 +0% 16641/kworker/2:1: 0% user + 0% kernel
 +0% 16697/kworker/u8:2: 0% user + 0% kernel
 +0% 17377/sh: 0% user + 0% kernel
 +0% 17379/ps: 0% user + 0% kernel
 +0% 17380/grep: 0% user + 0% kernel
20% TOTAL: 11% user + 8% kernel + 0% iowait + 0% softirq
null
----- pid 16313 at 2022-07-01 02:51:07 -----
Cmd line: com.afmobi.boomplayer
Build fingerprint: 'TECNO/LC7-GL/TECNO-LC7:10/QP1A.190711.020/BCF-GL-200612V304:user/release-keys'
ABI: 'arm'
Build type: optimized
Zygote loaded classes=9211 post zygote classes=6816
Dumping registered class loaders
#0 dalvik.system.PathClassLoader: [], parent #1
#1 java.lang.BootClassLoader: [], no parent
#2 dalvik.system.PathClassLoader: [/data/app/com.afmobi.boomplayer--xHbcuo1kM79VTfOrzSSfQ==/base.apk:/data/app/com.afmobi.boomplayer--xHbcuo1kM79VTfOrzSSfQ==/base.apk!classes2.dex:/data/app/com.afmobi.boomplayer--xHbcuo1kM79VTfOrzSSfQ==/base.apk!classes3.dex:/data/app/com.afmobi.boomplayer--xHbcuo1kM79VTfOrzSSfQ==/base.apk!classes4.dex], parent #1
#3 dalvik.system.DexClassLoader: [/data/user/0/com.afmobi.boomplayer/files/audience_network.dex], parent #2
#4 dalvik.system.InMemoryDexClassLoader: [/data/user/0/com.afmobi.boomplayer/Anonymous-DexFile@3764699927.jar], parent #2
#5 dalvik.system.InMemoryDexClassLoader: [/data/user/0/com.afmobi.boomplayer/Anonymous-DexFile@1904604828.jar], parent #2
#6 dalvik.system.DexClassLoader: [/data/user/0/com.afmobi.boomplayer/cache/1633031840514.jar], parent #2
Done dumping class loaders
Intern table: 44781 strong; 458 weak
JNI: CheckJNI is off; globals=768 (plus 49 weak)
Libraries: /data/app/com.afmobi.boomplayer--xHbcuo1kM79VTfOrzSSfQ==/lib/arm/libboomplay.so /data/app/com.afmobi.boomplayer--xHbcuo1kM79VTfOrzSSfQ==/lib/arm/libmmkv.so libandroid.so libcompiler_rt.so libdcfdecoderjni.so libjavacore.so libjavacrypto.so libjnigraphics.so libmedia_jni.so libopenjdk.so libsoundpool.so libwebviewchromium_loader.so (12)
Heap: 43% free, 13MB/23MB; 259751 objects
Dumping cumulative Gc timings
Start Dumping histograms for 19 iterations for concurrent copying
ProcessMarkStack:	Sum: 1.450s 99% C.I. 47.696ms-149.356ms Avg: 76.334ms Max: 149.356ms
ScanImmuneSpaces:	Sum: 240.086ms 99% C.I. 10.653ms-22.116ms Avg: 12.636ms Max: 22.733ms
VisitConcurrentRoots:	Sum: 85.016ms 99% C.I. 3.449ms-8.014ms Avg: 4.474ms Max: 8.014ms
ForwardSoftReferences:	Sum: 36.844ms 99% C.I. 0.431ms-10.354ms Avg: 1.939ms Max: 10.956ms
ClearFromSpace:	Sum: 32.034ms 99% C.I. 0.942ms-2.918ms Avg: 1.686ms Max: 2.918ms
FlipOtherThreads:	Sum: 26.176ms 99% C.I. 0.890ms-3.348ms Avg: 1.377ms Max: 3.473ms
EnqueueFinalizerReferences:	Sum: 24.256ms 99% C.I. 0.110ms-3.801ms Avg: 1.276ms Max: 3.801ms
SweepSystemWeaks:	Sum: 18.887ms 99% C.I. 459us-2007.250us Avg: 994.052us Max: 2017us
ScanCardsForSpace:	Sum: 15.981ms 99% C.I. 773us-1533.500us Avg: 841.105us Max: 1593us
GrayAllDirtyImmuneObjects:	Sum: 10.429ms 99% C.I. 414us-908us Avg: 548.894us Max: 908us
ProcessReferences:	Sum: 8.377ms 99% C.I. 4us-911.999us Avg: 220.447us Max: 928us
SweepLargeObjects:	Sum: 5.971ms 99% C.I. 74us-1614.500us Avg: 314.263us Max: 1656us
InitializePhase:	Sum: 4.661ms 99% C.I. 185us-888.250us Avg: 245.315us Max: 948us
VisitNonThreadRoots:	Sum: 3.503ms 99% C.I. 162us-248.812us Avg: 184.368us Max: 249us
RecordFree:	Sum: 2.890ms 99% C.I. 121us-289us Avg: 152.105us Max: 289us
ThreadListFlip:	Sum: 2.442ms 99% C.I. 60us-667us Avg: 128.526us Max: 667us
EmptyRBMarkBitStack:	Sum: 2.101ms 99% C.I. 24us-554us Avg: 110.578us Max: 554us
CopyingPhase:	Sum: 1.385ms 99% C.I. 46us-240.500us Avg: 72.894us Max: 242us
SweepAllocSpace:	Sum: 1.139ms 99% C.I. 24us-180us Avg: 59.947us Max: 180us
FlipThreadRoots:	Sum: 1.090ms 99% C.I. 3us-955us Avg: 57.368us Max: 1010us
MarkZygoteLargeObjects:	Sum: 914us 99% C.I. 40us-101us Avg: 48.105us Max: 101us
(Paused)GrayAllNewlyDirtyImmuneObjects:	Sum: 884us 99% C.I. 35us-103us Avg: 46.526us Max: 103us
MarkStackAsLive:	Sum: 840us 99% C.I. 19us-221us Avg: 44.210us Max: 221us
ReclaimPhase:	Sum: 422us 99% C.I. 14us-109us Avg: 22.210us Max: 109us
ResumeRunnableThreads:	Sum: 388us 99% C.I. 10us-72us Avg: 20.421us Max: 72us
ResumeOtherThreads:	Sum: 209us 99% C.I. 4us-52us Avg: 11us Max: 52us
SwapBitmaps:	Sum: 206us 99% C.I. 8us-16us Avg: 10.842us Max: 16us
(Paused)ClearCards:	Sum: 161us 99% C.I. 250ns-49869ns Avg: 385ns Max: 50000ns
Sweep:	Sum: 137us 99% C.I. 5us-11us Avg: 7.210us Max: 11us
(Paused)SetFromSpace:	Sum: 122us 99% C.I. 3us-41us Avg: 6.421us Max: 41us
(Paused)FlipCallback:	Sum: 102us 99% C.I. 4us-9us Avg: 5.368us Max: 9us
UnBindBitmaps:	Sum: 26us 99% C.I. 1us-2us Avg: 1.368us Max: 2us
Done Dumping histograms
concurrent copying paused:	Sum: 3.830ms 99% C.I. 115us-786us Avg: 201.578us Max: 786us
concurrent copying freed-bytes: Avg: 4404KB Max: 18MB Min: 1125KB
Freed-bytes histogram: 0:1,1280:2,2560:9,3840:3,5120:1,6400:2,19200:1
concurrent copying total time: 1.978s mean time: 104.106ms
concurrent copying freed: 1207168 objects with total size 81MB
concurrent copying throughput: 610297/s / 41MB/s  per cpu-time: 44521113/s / 42MB/s
Average major GC reclaim bytes ratio 0.337036 over 19 GC cycles
Average major GC copied live bytes ratio 0.642709 over 22 major GCs
Cumulative bytes moved 114951584
Cumulative objects moved 2445992
Peak regions allocated 549 (137MB) / 2048 (512MB)
Start Dumping histograms for 3 iterations for young concurrent copying
ProcessMarkStack:	Sum: 225.285ms 99% C.I. 15.143ms-180.096ms Avg: 75.095ms Max: 181.629ms
ScanCardsForSpace:	Sum: 74.696ms 99% C.I. 8.061ms-48.344ms Avg: 24.898ms Max: 48.749ms
CopyingPhase:	Sum: 56.119ms 99% C.I. 0.073ms-54.396ms Avg: 18.706ms Max: 54.595ms
ScanImmuneSpaces:	Sum: 51.237ms 99% C.I. 12.373ms-22.704ms Avg: 17.079ms Max: 22.704ms
ResumeOtherThreads:	Sum: 24.426ms 99% C.I. 0.015ms-24.040ms Avg: 8.142ms Max: 24.394ms
FlipOtherThreads:	Sum: 14.279ms 99% C.I. 1.193ms-11.823ms Avg: 4.759ms Max: 11.823ms
ClearFromSpace:	Sum: 12.127ms 99% C.I. 1.059ms-7.540ms Avg: 4.042ms Max: 7.558ms
VisitConcurrentRoots:	Sum: 8.914ms 99% C.I. 2.659ms-3.509ms Avg: 2.971ms Max: 3.509ms
ReclaimPhase:	Sum: 8.008ms 99% C.I. 0.981ms-4.374ms Avg: 2.669ms Max: 4.374ms
InitializePhase:	Sum: 7.474ms 99% C.I. 1.130ms-5.141ms Avg: 2.491ms Max: 5.143ms
VisitNonThreadRoots:	Sum: 6.645ms 99% C.I. 0.159ms-6.210ms Avg: 2.215ms Max: 6.270ms
SweepArray:	Sum: 5.532ms 99% C.I. 0.234ms-4.299ms Avg: 1.844ms Max: 4.313ms
SweepSystemWeaks:	Sum: 5.138ms 99% C.I. 0.484ms-3.268ms Avg: 1.712ms Max: 3.268ms
ThreadListFlip:	Sum: 4.656ms 99% C.I. 0.178ms-4.141ms Avg: 1.552ms Max: 4.191ms
EnqueueFinalizerReferences:	Sum: 3.562ms 99% C.I. 0.724ms-1.627ms Avg: 1.187ms Max: 1.627ms
ProcessReferences:	Sum: 1.855ms 99% C.I. 4us-988us Avg: 309.166us Max: 992us
GrayAllDirtyImmuneObjects:	Sum: 1.481ms 99% C.I. 425us-528us Avg: 493.666us Max: 528us
ForwardSoftReferences:	Sum: 1.432ms 99% C.I. 135us-964us Avg: 477.333us Max: 964us
EmptyRBMarkBitStack:	Sum: 821us 99% C.I. 126us-473us Avg: 273.666us Max: 473us
FlipThreadRoots:	Sum: 532us 99% C.I. 7us-366us Avg: 177.333us Max: 366us
RecordFree:	Sum: 467us 99% C.I. 2us-160us Avg: 77.833us Max: 160us
ResetStack:	Sum: 279us 99% C.I. 9us-256us Avg: 93us Max: 256us
FreeList:	Sum: 248us 99% C.I. 9us-85us Avg: 49.600us Max: 85us
ResumeRunnableThreads:	Sum: 206us 99% C.I. 51us-79us Avg: 68.666us Max: 79us
(Paused)GrayAllNewlyDirtyImmuneObjects:	Sum: 159us 99% C.I. 50us-55us Avg: 53us Max: 55us
MarkZygoteLargeObjects:	Sum: 105us 99% C.I. 33us-39us Avg: 35us Max: 39us
SwapBitmaps:	Sum: 26us 99% C.I. 6us-13us Avg: 8.666us Max: 13us
(Paused)SetFromSpace:	Sum: 21us 99% C.I. 4us-13us Avg: 7us Max: 13us
(Paused)FlipCallback:	Sum: 19us 99% C.I. 5us-7us Avg: 6.333us Max: 7us
(Paused)ClearCards:	Sum: 15us 99% C.I. 250ns-2000ns Avg: 227ns Max: 2000ns
UnBindBitmaps:	Sum: 7us 99% C.I. 2us-3us Avg: 2.333us Max: 3us
Done Dumping histograms
young concurrent copying paused:	Sum: 4.876ms 99% C.I. 0.251ms-4.268ms Avg: 1.625ms Max: 4.268ms
young concurrent copying freed-bytes: Avg: 8510KB Max: 10MB Min: 3763KB
Freed-bytes histogram: 2560:1,10240:2
young concurrent copying total time: 515.771ms mean time: 171.923ms
young concurrent copying freed: 429045 objects with total size 24MB
young concurrent copying throughput: 833097/s / 48MB/s  per cpu-time: 189456811/s / 180MB/s
Average minor GC reclaim bytes ratio 0.486683 over 3 GC cycles
Average minor GC copied live bytes ratio 0.125081 over 3 minor GCs
Cumulative bytes moved 3068240
Cumulative objects moved 54940
Peak regions allocated 549 (137MB) / 2048 (512MB)
Total time spent in GC: 2.493s
Mean GC size throughput: 36MB/s
Mean GC object throughput: 655976 objects/s
Total number of allocations 1895624
Total bytes allocated 104MB
Total bytes freed 91MB
Free memory 10MB
Free memory until GC 10MB
Free memory until OOME 498MB
Total memory 23MB
Max memory 512MB
Zygote space size 1536KB
Total mutator paused time: 8.706ms
Total time waiting for GC to complete: 72.072us
Total GC count: 22
Total GC time: 2.493s
Total blocking GC count: 19
Total blocking GC time: 1.987s
Histogram of GC count per 10000 ms: 0:1,1:8,2:3,3:2
Histogram of blocking GC count per 10000 ms: 0:1,1:9,2:4
Native bytes total: 41013864 registered: 209512
Total native bytes at last GC: 40833148
Skip  /data/user/0/com.afmobi.boomplayer/Anonymous-DexFile@3764699927.jar for GetKeyValueStoreSize == 0 
Skip  /data/user/0/com.afmobi.boomplayer/Anonymous-DexFile@1904604828.jar for GetKeyValueStoreSize == 0 
/system/framework/oat/arm/android.hidl.base-V1.0-java.odex: quicken
/system/framework/oat/arm/android.hidl.manager-V1.0-java.odex: quicken
/data/app/com.afmobi.boomplayer--xHbcuo1kM79VTfOrzSSfQ==/oat/arm/base.odex: speed-profile
/system/framework/oat/arm/org.apache.http.legacy.odex: speed-profile
Current JIT code cache size: 863KB
Current JIT data cache size: 433KB
Current JIT mini-debug-info size: 57KB
Current JIT capacity: 3072KB
Current number of JIT JNI stub entries: 3
Current number of JIT code cache entries: 775
Total number of JIT compilations: 960
Total number of JIT compilations for on stack replacement: 29
Total number of JIT code cache collections: 10
Memory used for stack maps: Avg: 398B Max: 9252B Min: 16B
Memory used for compiled code: Avg: 1154B Max: 17KB Min: 2B
Memory used for profiling info: Avg: 177B Max: 8104B Min: 16B
Start Dumping histograms for 1934 iterations for JIT timings
Compiling:	Sum: 3.762s 99% C.I. 0.106ms-35.775ms Avg: 3.902ms Max: 190.564ms
Generate JIT debug info:	Sum: 296.629ms 99% C.I. 45us-10639.999us Avg: 308.988us Max: 33859us
TrimMaps:	Sum: 56.180ms 99% C.I. 12us-279.857us Avg: 58.278us Max: 885us
Code cache collection:	Sum: 20.743ms 99% C.I. 1.126ms-3.755ms Avg: 2.074ms Max: 3.785ms
Done Dumping histograms
Memory used for compilation: Avg: 111KB Max: 3457KB Min: 0B
ProfileSaver total_bytes_written=76873
ProfileSaver total_number_of_writes=4
ProfileSaver total_number_of_code_cache_queries=7
ProfileSaver total_number_of_skipped_writes=3
ProfileSaver total_number_of_failed_writes=0
ProfileSaver total_ms_of_sleep=127808
ProfileSaver total_ms_of_work=142
ProfileSaver max_number_profile_entries_cached=0
ProfileSaver total_number_of_hot_spikes=27
ProfileSaver total_number_of_wake_ups=27
Number of JIT inline cache deoptimizations: 80

suspend all histogram:	Sum: 11.629ms 99% C.I. 7us-2737.920us Avg: 135.220us Max: 4162us
DALVIK THREADS (121):
"Signal Catcher" daemon prio=5 tid=7 Runnable
  | group="system" sCount=0 dsCount=0 flags=0 obj=0x13a03570 self=0x98c56800
  | sysTid=16324 nice=0 cgrp=default sched=0/0 handle=0x89a64230
  | state=R schedstat=( 23772847 1407308 4 ) utm=2 stm=0 core=3 HZ=100
  | stack=0x89969000-0x8996b000 stackSize=1008KB
  | held mutexes= "mutator lock"(shared held)
  native: #00 pc 002fdd8f  /apex/com.android.runtime/lib/libart.so (art::DumpNativeStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, int, BacktraceMap*, char const*, art::ArtMethod*, void*, bool)+78)
  native: #01 pc 003a66bb  /apex/com.android.runtime/lib/libart.so (art::Thread::DumpStack(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+358)
  native: #02 pc 003a2e93  /apex/com.android.runtime/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool, BacktraceMap*, bool) const+34)
  native: #03 pc 003bb8b5  /apex/com.android.runtime/lib/libart.so (art::DumpCheckpoint::Run(art::Thread*)+576)
  native: #04 pc 003b6265  /apex/com.android.runtime/lib/libart.so (art::ThreadList::RunCheckpoint(art::Closure*, art::Closure*)+296)
  native: #05 pc 003b5985  /apex/com.android.runtime/lib/libart.so (art::ThreadList::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, bool)+1416)
  native: #06 pc 003b5319  /apex/com.android.runtime/lib/libart.so (art::ThreadList::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char>>&)+640)
  native: #07 pc 0037fe1b  /apex/com.android.runtime/lib/libart.so (art::Runtime::DumpForSigQuit(std::__1::basic_ostream<char, std::__1::char_traits<char>>&)+130)
  native: #08 pc 0038e78d  /apex/com.android.runtime/lib/libart.so (art::SignalCatcher::HandleSigQuit()+1036)
  native: #09 pc 0038dbf7  /apex/com.android.runtime/lib/libart.so (art::SignalCatcher::Run(void*)+242)
  native: #10 pc 000a60b3  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+20)
  native: #11 pc 00060783  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)
  (no managed stack frames)

"main" prio=5 tid=1 Native
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x70e18460 self=0xaed5ce00
  | sysTid=16313 nice=0 cgrp=default sched=1073741825/1 handle=0xaf302dc0
  | state=S schedstat=( 8513202400 140779436 8783 ) utm=724 stm=127 core=0 HZ=100
  | stack=0xbe5fa000-0xbe5fc000 stackSize=8192KB
  | held mutexes=
  kernel: (couldn't read /proc/self/task/16313/stack)
  native: #00 pc 000962f0  /apex/com.android.runtime/lib/bionic/libc.so (__ioctl+8)
  native: #01 pc 00064c9d  /apex/com.android.runtime/lib/bionic/libc.so (ioctl+28)
  native: #02 pc 0003aa81  /system/lib/libbinder.so (android::IPCThreadState::talkWithDriver(bool)+208)
  native: #03 pc 0003b97f  /system/lib/libbinder.so (android::IPCThreadState::waitForResponse(android::Parcel*, int*)+26)
  native: #04 pc 0003b791  /system/lib/libbinder.so (android::IPCThreadState::transact(int, unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+112)
  native: #05 pc 00033ed1  /system/lib/libbinder.so (android::BpBinder::transact(unsigned int, android::Parcel const&, android::Parcel*, unsigned int)+36)
  native: #06 pc 000ddceb  /system/lib/libandroid_runtime.so (android_os_BinderProxy_transact(_JNIEnv*, _jobject*, int, _jobject*, _jobject*, int)+82)
  at android.os.BinderProxy.transactNative(Native method)
  at android.os.BinderProxy.transact(BinderProxy.java:543)
  at android.webkit.IWebViewUpdateService$Stub$Proxy.waitForAndGetProvider(IWebViewUpdateService.java:316)
  at android.webkit.WebViewFactory.getWebViewContextAndSetProvider(WebViewFactory.java:332)
  at android.webkit.WebViewFactory.getProviderClass(WebViewFactory.java:402)
  at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:252)
  - locked <0x02260685> (a java.lang.Object)
  at android.webkit.WebView.getFactory(WebView.java:2551)
  at android.webkit.WebView.ensureProviderCreated(WebView.java:2545)
  at android.webkit.WebView.setOverScrollMode(WebView.java:2613)
  at android.view.View.<init>(View.java:5072)
  at android.view.View.<init>(View.java:5213)
  at android.view.ViewGroup.<init>(ViewGroup.java:676)
  at android.widget.AbsoluteLayout.<init>(AbsoluteLayout.java:56)
  at android.webkit.WebView.<init>(WebView.java:410)
  at android.webkit.WebView.<init>(WebView.java:353)
  at android.webkit.WebView.<init>(WebView.java:336)
  at android.webkit.WebView.<init>(WebView.java:323)
  at android.webkit.WebView.<init>(WebView.java:313)
  at com.google.android.gms.internal.ads.zzcpi.<init>(com.google.android.gms:play-services-ads@@20.6.0:1)
  at com.google.android.gms.internal.ads.zzcoy.zza(com.google.android.gms:play-services-ads@@20.6.0:4)
  at com.google.android.gms.internal.ads.zzcpb.zza(com.google.android.gms:play-services-ads@@20.6.0:8)
  at com.google.android.gms.internal.ads.zzcoz.zza(com.google.android.gms:play-services-ads@@20.6.0:3)
  at com.google.android.gms.internal.ads.zzfxn.zza(com.google.android.gms:play-services-ads@@20.6.0:1)
  at com.google.android.gms.internal.ads.zzfwz.run(com.google.android.gms:play-services-ads@@20.6.0:4)
  at com.google.android.gms.internal.ads.zzfxp.run(com.google.android.gms:play-services-ads@@20.6.0:1)
  at android.os.Handler.handleCallback(Handler.java:883)
  at android.os.Handler.dispatchMessage(Handler.java:100)
  at com.google.android.gms.internal.ads.zzfpj.zza(com.google.android.gms:play-services-ads-lite@@20.6.0:1)
  at com.google.android.gms.ads.internal.util.zzf.zza(com.google.android.gms:play-services-ads@@20.6.0:1)
  at com.google.android.gms.internal.ads.zzfpj.dispatchMessage(com.google.android.gms:play-services-ads-lite@@20.6.0:1)
  at android.os.Looper.loop(Looper.java:264)
  at android.app.ActivityThread.main(ActivityThread.java:7581)
  at java.lang.reflect.Method.invoke(Native method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)

"Jit thread pool worker thread 0" daemon prio=5 tid=2 Native
  | group="main" sCount=1 dsCount=0 flags=1 obj=0x13a034f8 self=0x9bc06000
  | sysTid=16319 nice=0 cgrp=default sched=0/0 handle=0x9c0ccd90
  | state=S schedstat=( 3896098233 973023559 3235 ) utm=325 stm=64 core=2 HZ=100
  | stack=0x9bfce000-0x9bfd0000 stackSize=1023KB
  | held mutexes=
  kernel: (couldn't read /proc/self/task/16319/stack)
  native: #00 pc 0005a7d0  /apex/com.android.runtime/lib/bionic/libc.so (syscall+28)
  native: #01 pc 000e44e5  /apex/com.android.runtime/lib/libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*)+80)
  native: #02 pc 003bcbbf  /apex/com.android.runtime/lib/libart.so (art::ThreadPool::GetTask(art::Thread*)+174)
  native: #03 pc 003bc345  /apex/com.android.runtime/lib/libart.so (art::ThreadPoolWorker::Run()+72)
  native: #04 pc 003bbf97  /apex/com.android.runtime/lib/libart.so (art::ThreadPoolWorker::Callback(void*)+90)
  native: #05 pc 000a60b3  /apex/com.android.runtime/lib/bionic/libc.so (__pthread_start(void*)+20)
  native: #06 pc 00060783  /apex/com.android.runtime/lib/bionic/libc.so (__start_thread+30)
  (no managed stack frames)
【SDK Version】
com.google.android.gms:play-services-ads@@20.6.0

**Comment by hamza-mughal5593** [comment]
Write this code in your Manifeast application 

 <application>
      ...
      <meta-data
          android:name="com.google.android.gms.ads.flag.OPTIMIZE_INITIALIZATION"
          android:value="true"/>
  </application>

**Comment by NVentimiglia** [comment]
For more details see : https://developers.google.com/admob/android/optimize-initialization
