### ISSUE TITLE
OOM in Video ads

### ISSUE THREAD

**Issue by ankush38u** [googleads/googleads-mobile-android-examples#46]
Crashes on some devices with OutOfMemory while used internally by Firebase Ads.

Here is the stacktrace from crashlytics:

Fatal Exception: java.lang.OutOfMemoryError
       at com.google.android.gms.ads.exoplayer1.upstream.g.a(:com.google.android.gms.DynamiteModulesA:51)
       at com.google.android.gms.ads.exoplayer1.extractor.k.b(:com.google.android.gms.DynamiteModulesA:432)
       at com.google.android.gms.ads.exoplayer1.extractor.c.a(:com.google.android.gms.DynamiteModulesA:2384)
       at com.google.android.gms.ads.exoplayer1.extractor.mp4.f.b(:com.google.android.gms.DynamiteModulesA:311)
       at com.google.android.gms.ads.exoplayer1.extractor.mp4.f.a(:com.google.android.gms.DynamiteModulesA:108)
       at com.google.android.gms.ads.exoplayer1.extractor.h.c(:com.google.android.gms.DynamiteModulesA:615)
       at com.google.android.gms.ads.exoplayer1.upstream.t.run(:com.google.android.gms.DynamiteModulesA:242)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

Happens on android 4,5,6 all, frequecy is around 12-15 in a month.

**Comment by temrich** [comment]
Hi, the GitHub issues tracker is for issues and feature requests for our Android sample apps. Please direct all SDK issues to our developer forum: https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android

Thank you!
