### ISSUE TITLE
Unable to start activity ComponentInfo{com.**.***/com.**.***.activities.MainActivity2}: android.util.AndroidRuntimeException: android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview

### ISSUE THREAD

**Issue by androidapkr** [googleads/googleads-mobile-android-examples#51]
Reproduce issue: 

`Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.**.***/com.**.***.activities.MainActivity2}: android.util.AndroidRuntimeException: android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2521)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595)
       at android.app.ActivityThread.access$800(ActivityThread.java:178)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5631)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)
Caused by android.util.AndroidRuntimeException: android.content.pm.PackageManager$NameNotFoundException: com.google.android.webview
       at android.webkit.WebViewFactory.getFactoryClass(WebViewFactory.java:174)
       at android.webkit.WebViewFactory.getProvider(WebViewFactory.java:109)
       at android.webkit.CookieManager.getInstance(CookieManager.java:42)
       at com.google.android.gms.ads.internal.util.aq.b(:com.google.android.gms.DynamiteModulesA:491)
       at com.google.android.gms.ads.internal.zzc.zza(:com.google.android.gms.DynamiteModulesA:550)
       at com.google.android.gms.ads.internal.zzc.zza(:com.google.android.gms.DynamiteModulesA:140)
       at com.google.android.gms.ads.internal.ad.a(:com.google.android.gms.DynamiteModulesA:148)
       at com.google.android.gms.ads.internal.zza.zza(:com.google.android.gms.DynamiteModulesA:317)
       at com.google.android.gms.ads.internal.client.zzy.onTransact(:com.google.android.gms.DynamiteModulesA:81)
       at android.os.Binder.transact(Binder.java:385)
       at com.google.android.gms.ads.internal.client.zzu$zza$zza.zzef(Unknown Source)
       at com.google.android.gms.ads.internal.client.zzaf.isLoaded(Unknown Source)
       at com.google.android.gms.ads.InterstitialAd.isLoaded(Unknown Source)
       at com.**.***.activities.MainActivity2.requestNewInterstitial(Unknown Source)
       at com.**.***.activities.MainActivity2.initAdViews(Unknown Source)
       at com.**.***.activities.MainActivity2.onCreate(Unknown Source)
       at android.app.Activity.performCreate(Activity.java:6092)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1112)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2468)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2595)
       at android.app.ActivityThread.access$800(ActivityThread.java:178)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1470)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.app.ActivityThread.main(ActivityThread.java:5631)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:959)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:754)`

**Comment by ericleich** [comment]
Hi there,

This part of the stack trace:

`com.google.android.gms.ads.InterstitialAd.isLoaded(Unknown Source) at com.**.***.activities.MainActivity2.requestNewInterstitial(Unknown Source) at com.**.***.activities.MainActivity2.initAdViews(Unknown Source) at com.**.***.activities.MainActivity2.onCreate(Unknown Source) at android.app.Activity.performCreate(Activity.java:6092) at `

makes me believe that your code is significantly different enough from the InterstitialExample. Is this crash reproducible with the interstitial example? If not, I recommend going to the [Google Mobile Ads SDK developer forum](https://groups.google.com/group/google-admob-ads-sdk) and posing your question there along with your code showing how you implemented the SDK, so the support team can help you out.
