### ISSUE TITLE
crash java.lang.VerifyError java.lang.NoClassDefFoundError

### ISSUE THREAD

**Issue by pigerj** [googleads/googleads-mobile-android-examples#545]
today after upgrading to latest sdk's version and uploading a release appbundle, crashlytics report new crashes.
this is the related versions:

    implementation 'com.google.android.gms:play-services-ads:22.0.0'
    implementation 'com.unity3d.ads:unity-ads:4.5.0'
    implementation 'com.google.ads.mediation:unity:4.6.1.0'
    implementation 'com.google.ads.mediation:facebook:6.13.7.0'
    
this is the crash call stack:

    
Fatal Exception: java.lang.NoClassDefFoundError: e.c.b.c.h.a.bl1
       at com.google.android.gms.internal.ads.zzchk.<init>(zzchk.java:30)
       at com.google.android.gms.internal.ads.zzchi.zzg(zzchi.java:5)
       at com.google.android.gms.internal.ads.zzeiy.zzb(zzeiy.java:20)
       at com.google.android.gms.internal.ads.zzeim.zzd(zzeim.java:1)
       at com.google.android.gms.internal.ads.zzehf.zzg(zzehf.java:1)
       at com.google.android.gms.ads.AdLoader.zza(AdLoader.java:1)
       at com.google.android.gms.ads.zza.run(zza.java:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

Caused by java.lang.VerifyError: Verifier rejected class e.c.b.c.h.a.bl1: java.lang.Object e.c.b.c.h.a.bl1.b() failed to verify: java.lang.Object e.c.b.c.h.a.bl1.b(): [0x2E] register v3 has type Reference: java.lang.Object but expected Precise Reference: e.c.b.c.h.a.nh0 (declaration of 'e.c.b.c.h.a.bl1' appears in base.apk)
       at com.google.android.gms.internal.ads.zzcio.<init>(zzcio.java:26)
       at com.google.android.gms.internal.ads.zzcim.zzj(zzcim.java:7)
       at com.google.android.gms.internal.ads.zzeuo.zzb(zzeuo.java:44)
       at com.google.android.gms.internal.ads.zzehh.zzf(zzehh.java:5)
       at com.google.android.gms.internal.ads.zzehh.zzaa(zzehh.java:2)
       at com.google.android.gms.ads.internal.client.zzea.zzm(zzea.java:26)
       at com.google.android.gms.ads.zzc.run(zzc.java:1)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.java:665)

**Comment by idunnololz** [comment]
I have the same issue. I built a release APK, however I was unable to reproduce the crash on real devices even with the release APK. What ended up reproducing the crash was installing the release APK on an emulator.

I was able to workaround the crash by adding the following to my proguard
```
-keep class com.google.android.gms.internal.ads.** { *; }
```

**Comment by NVentimiglia** [comment]
This is a known issue and we are working on a fix.

As a work around you can hard code the maximum version of the google mobile ads Android sdk in the `GoogleMobileAdsDependencies.xml` file.

```
<dependencies>
  <androidPackages>
    <androidPackage spec="com.google.android.gms:play-services-ads:[22.3.0]">
      <repositories>
        <repository>https://maven.google.com/</repository>
      </repositories>
    </androidPackage>
  </androidPackages>

  <iosPods>
    <iosPod name="Google-Mobile-Ads-SDK" version="~> 10.9">
      <sources>
        <source>https://github.com/CocoaPods/Specs</source>
      </sources>
    </iosPod>
  </iosPods>
</dependencies>
```

**Comment by NVentimiglia** [comment]
Additionally you can disable external dependency resolution as described [here](https://developers.google.com/admob/unity/quick-start#include_external_dependencies)

We are working on a fix, if you run into further issues please reopen this ticket.
