### ISSUE TITLE
crash java.lang.NullPointerException:

### ISSUE THREAD

**Issue by XiaoJianXD** [googleads/googleads-mobile-android-examples#546]
SDK version: 22.0.0
Android version: 6.0.1
Nexus 5X

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getVisibility()' on a null object reference
       at com.google.android.gms.ads.internal.util.AdUtil.isViewVisible(AdUtil.java:1099)
       at com.google.android.gms.ads.internal.activeview.PositionWatcher.fireMeasurements(PositionWatcher.java:360)
       at com.google.android.gms.ads.internal.activeview.PositionWatcher.lambda$fireMeasurementsPost$0$com-google-android-gms-ads-internal-activeview-PositionWatcher(PositionWatcher.java:140)
       at com.google.android.gms.ads.internal.activeview.PositionWatcher$$ExternalSyntheticLambda0.run(D8$$SyntheticClass)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at com.google.android.gms.libs.punchclock.threads.TracingHandler.dispatchMessageTraced(TracingHandler.java:257)
       at com.google.android.gms.ads.internal.util.AdMobHandler.dispatchMessageTraced(AdMobHandler.java:39)
       at com.google.android.gms.libs.punchclock.threads.TracingHandler.dispatchMessage(TracingHandler.java:214)
       at android.os.Looper.loop(Looper.java:148)
       at android.app.ActivityThread.main(ActivityThread.java:5421)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

**Comment by JillSong** [comment]
Hi @XiaoJianXD ,  Was this crash generated from this repo? Can you share steps to reproduce this crash?

**Comment by JillSong** [comment]
Hi @XiaoJianXD , looks like the crash is related to the Google Mobile Ads SDK and not rooted from the sample code. If you are still experiencing this issue can you please open a case on the [google mobile ads support forum](https://groups.google.com/g/google-admob-ads-sdk)? Please include a network trace and device trace of the incident so we can look into this for you.
