### ISSUE TITLE
java.lang.NullPointerException - Attempt to invoke virtual method 'int android.view.View.getWidth()' on a null object reference

### ISSUE THREAD

**Issue by stuhua** [googleads/googleads-mobile-android-examples#573]
SDK version: 21.5.0

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getWidth()' on a null object reference
       at com.google.android.gms.internal.ads.zzaqk.zzk(com.google.android.gms:play-services-ads@@21.5.0:4)
       at com.google.android.gms.internal.ads.zzapc.zzh(com.google.android.gms:play-services-ads@@21.5.0:4)
       at com.google.android.gms.ads.internal.zzi.zzh(com.google.android.gms:play-services-ads@@21.5.0:8)
       at com.google.android.gms.internal.ads.zzcwh.zzs(com.google.android.gms:play-services-ads@@21.5.0:3)
       at com.google.android.gms.internal.ads.zzcwh.zzf(com.google.android.gms:play-services-ads@@21.5.0)
       at com.google.android.gms.internal.ads.zzcwe.run(com.google.android.gms:play-services-ads@@21.5.0:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

![image](https://github.com/googleads/googleads-mobile-android-examples/assets/5968293/bf0bad11-52c1-455d-a774-38ee512bb2c4)

**Comment by NVentimiglia** [comment]
Hi @stuhua 

Can you add some additional details?

- What version of the SDK are you using.
- A complete crash log.
- A snippet of the code which you ran which caused this crash.

**Comment by stuhua** [comment]
- admob version: 21.5.0.
- The above provided is already a complete log.
- This is an online bug. We did not find a path to reproduce it locally, but I saw that this view is a weak reference and has not been judged empty. I don’t know if others have encountered it.
![image](https://github.com/googleads/googleads-mobile-android-examples/assets/5968293/78df8744-d968-4c28-8962-c2a8c7bac493)

**Comment by NVentimiglia** [comment]
@stuhua 

This is not enough to identify the source of the bug. I recommend opening up a bug case on the [official google ads support forum](https://groups.google.com/g/google-admob-ads-sdk).
