### ISSUE TITLE
RewardedVideoAd：There was a problem getting an ad response. ErrorCode: 0

### ISSUE THREAD

**Issue by LoveMyBaby** [googleads/googleads-mobile-android-examples#65]
admob load faild,There was a problem getting an ad response. ErrorCode: 0
so i clean play services data(Storage -> Manage Space -> Clear all data) and then ：

com.google.ads.rewardedvideoexample E/DynamitePackage: Failed to load ads dynamite module.
                                                                                    android.os.RemoteException
                                                                                        at dca.<init>(:com.google.android.gms:37)
                                                                                        at dca.a(:com.google.android.gms:23)
                                                                                        at com.google.android.gms.ads.MobileAdsSettingManagerCreatorImpl.getMobileAdsSettingManager(:com.google.android.gms:37)
                                                                                        at com.google.android.gms.ads.internal.client.q.onTransact(:com.google.android.gms:55)
                                                                                        at android.os.Binder.transact(Binder.java:499)
                                                                                        at com.google.android.gms.internal.zzez$zza$zza.zza(Unknown Source)
                                                                                        at com.google.android.gms.internal.zzfj.zzm(Unknown Source)
                                                                                        at com.google.android.gms.internal.zzek$5.zzeL(Unknown Source)
                                                                                        at com.google.android.gms.internal.zzek$5.zzeJ(Unknown Source)
                                                                                        at com.google.android.gms.internal.zzek$zza.zzeR(Unknown Source)
                                                                                        at com.google.android.gms.internal.zzek.zza(Unknown Source)
                                                                                        at com.google.android.gms.internal.zzek.zzl(Unknown Source)
                                                                                        at com.google.android.gms.internal.zzfh.zza(Unknown Source)
                                                                                        at com.google.android.gms.ads.MobileAds.initialize(Unknown Source)
                                                                                        at com.google.android.gms.ads.MobileAds.initialize(Unknown Source)
                                                                                        at com.google.ads.rewardedvideoexample.MainActivity.onCreate(MainActivity.java:42)
                                                                                        at android.app.Activity.performCreate(Activity.java:6679)
                                                                                        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
                                                                                        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2618)
                                                                                        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                                        at android.app.ActivityThread.-wrap12(ActivityThread.java)
                                                                                        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1477)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                        at android.os.Looper.loop(Looper.java:154)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:6126)
                                                                                        at java.lang.reflect.Method.invoke(Native Method)
                                                                                        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                                        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)
com.google.ads.rewardedvideoexample E/Ads: This app is using a lightweight version of the Google Mobile Ads SDK that requires the latest Google Play services to be installed, but Google Play services is either missing or out of date.
com.google.ads.rewardedvideoexample E/Ads: This app is using a lightweight version of the Google Mobile Ads SDK that requires the latest Google Play services to be installed, but Google Play services is either missing or out of date.
phone play service is latest(10.5.53 beta update from 10.2.98)

**Comment by ericleich** [comment]
This does happen the first time if you open the app and request an ad right after clearing all data, since play services takes some time to restart. The error `This app is using a lightweight version of the Google Mobile Ads SDK that requires the latest Google Play services to be installed, but Google Play services is either missing or out of date.` is a little misleading in this situation, since you probably aren't using the lightweight version of the SDK (i.e. you aren't using `play-services-ads-lite`). It's just that, as mentioned above, play services isn't fully spun up yet. 

If you wait a few minutes, this error should disappear.

**Comment by LoveMyBaby** [comment]
@ericleich
04-06 10:25:49.444 13522-13522/com.google.ads.rewardedvideoexample I/Ads: Starting ad request.
04-06 10:25:49.444 13522-13522/com.google.ads.rewardedvideoexample I/Ads: Use AdRequest.Builder.addTestDevice("719823A0BC6D5B2856ED1618FD527344") to get test ads on this device.
04-06 10:25:49.766 13522-15214/com.google.ads.rewardedvideoexample W/Ads: Fail to instantiate adapter com.google.DummyAdapter
                                                                          android.os.RemoteException
                                                                              at com.google.android.gms.internal.zzjz.zzav(Unknown Source)
                                                                              at com.google.android.gms.internal.zzjz.zzau(Unknown Source)
                                                                              at com.google.android.gms.internal.zzjz.zzas(Unknown Source)
                                                                              at com.google.android.gms.internal.zzka$zza.onTransact(Unknown Source)
                                                                              at android.os.Binder.transact(Binder.java:499)
                                                                              at com.google.android.gms.ads.internal.mediation.client.d.a(:com.google.android.gms.DynamiteModulesA:94)
                                                                              at com.google.android.gms.ads.internal.reward.c.b(:com.google.android.gms.DynamiteModulesA:229)
                                                                              at com.google.android.gms.ads.internal.reward.mediation.k.a(:com.google.android.gms.DynamiteModulesA:1140)
                                                                              at com.google.android.gms.ads.internal.util.b.run(:com.google.android.gms.DynamiteModulesA:19)
                                                                              at com.google.android.gms.ads.internal.util.ag.call(:com.google.android.gms.DynamiteModulesA:1055)
                                                                              at com.google.android.gms.ads.internal.util.ah.run(:com.google.android.gms.DynamiteModulesA:75)
                                                                              at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                              at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                              at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                              at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                              at java.lang.Thread.run(Thread.java:761)
04-06 10:25:49.773 13522-13522/com.google.ads.rewardedvideoexample W/Ads: Failed to load ad: 3







------------------ 原始邮件 ------------------
发件人: "Eric Leichtenschlag";<notifications@github.com>;
发送时间: 2017年4月6日(星期四) 凌晨1:55
收件人: "googleads/googleads-mobile-android-examples"<googleads-mobile-android-examples@noreply.github.com>; 
抄送: "KEN"<378434243@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [googleads/googleads-mobile-android-examples] RewardedVideoAd：There was a problem getting an ad response. ErrorCode: 0 (#65)




This does happen the first time if you open the app and request an ad right after clearing all data, since play services takes some time to restart. The error This app is using a lightweight version of the Google Mobile Ads SDK that requires the latest Google Play services to be installed, but Google Play services is either missing or out of date. is a little misleading in this situation, since you probably aren't using the lightweight version of the SDK (i.e. you aren't using play-services-ads-lite). It's just that, as mentioned above, play services isn't fully spun up yet.
 
If you wait a few minutes, this error should disappear.

**Comment by ericleich** [comment]
DummyAdapter means there are 0 eligible networks the rewarded video mediation chain. This can happen if you disabled the AdMob network by setting 0.00 eCPM, and have no other mediation networks associated with your ad unit. Try using `ca-app-pub-3940256099942544/5224354917`, which is the sample ad unit from the [Rewarded video docs](https://firebase.google.com/docs/admob/android/rewarded-video). If this works, it confirms it's an ad unit setting issue.

**Comment by LoveMyBaby** [comment]
@ericleich
I use the sample:
https://github.com/googleads/googleads-mobile-android-examples/tree/master/admob/RewardedVideoExample
It is not work, and Admob load fiald: error code 3
 




------------------ 原始邮件 ------------------
发件人: "Eric Leichtenschlag";<notifications@github.com>;
发送时间: 2017年4月6日(星期四) 中午11:11
收件人: "googleads/googleads-mobile-android-examples"<googleads-mobile-android-examples@noreply.github.com>; 
抄送: "KEN"<378434243@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [googleads/googleads-mobile-android-examples] RewardedVideoAd：There was a problem getting an ad response. ErrorCode: 0 (#65)




DummyAdapter means there are 0 eligible networks the rewarded video mediation chain. This can happen if you disabled the AdMob network by setting 0.00 eCPM, and have no other mediation networks associated with your ad unit. Try using ca-app-pub-3940256099942544/5224354917, which is the sample ad unit from the Rewarded video docs. If this works, it confirms it's an ad unit setting issue.

**Comment by ericleich** [comment]
Are you running on emulator? There's a known issue where rewarded isn't serving on emulator, which we're working on but it'll be another 1-2 weeks before it's fixed. In the meantime, do you have a device you can try running this on?

**Comment by LoveMyBaby** [comment]
@ericleich
running on my phone OnePlusOne(Android N 7.1.1)






------------------ 原始邮件 ------------------
发件人: "Eric Leichtenschlag";<notifications@github.com>;
发送时间: 2017年4月7日(星期五) 凌晨0:48
收件人: "googleads/googleads-mobile-android-examples"<googleads-mobile-android-examples@noreply.github.com>; 
抄送: "KEN"<378434243@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [googleads/googleads-mobile-android-examples] RewardedVideoAd：There was a problem getting an ad response. ErrorCode: 0 (#65)




Are you running on emulator? There's a known issue where rewarded isn't serving on emulator, which we're working on but it'll be another 1-2 weeks before it's fixed. In the meantime, do you have a device you can try running this on?

**Comment by LoveMyBaby** [comment]
@ericleich
And now , I use my APP_ID and AD_UNIT_ID with mediation Vungle, it can load and display video normal.
but the sample APP_ID and AD_UNIT_ID Still failed to load, errorcode:3. So I think the cause of this error is sample APP_ID and AD_UNIT_ID.


 





------------------ 原始邮件 ------------------
发件人: "Eric Leichtenschlag";<notifications@github.com>;
发送时间: 2017年4月7日(星期五) 凌晨0:48
收件人: "googleads/googleads-mobile-android-examples"<googleads-mobile-android-examples@noreply.github.com>; 
抄送: "KEN"<378434243@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [googleads/googleads-mobile-android-examples] RewardedVideoAd：There was a problem getting an ad response. ErrorCode: 0 (#65)




Are you running on emulator? There's a known issue where rewarded isn't serving on emulator, which we're working on but it'll be another 1-2 weeks before it's fixed. In the meantime, do you have a device you can try running this on?

**Comment by ericleich** [comment]
Is there any chance you have the [Creative Preview](https://play.google.com/store/apps/details?id=com.google.android.apps.audition&hl=en) app installed on your device. That ad unit points to a rewarded video house ad campaign for this app and has the AdMob network turned off. If the app is installed, the ad is ineliglble, and no other ads are configured to serve to this ad unit.

I was just able to successfully run the rewarded sample in this repo on a device that didn't have this app installed.

**Comment by LoveMyBaby** [comment]
@ericleich
  hi,ericleich.
  I have installed  Creative Preview.
  1. it only show MoPub ads(Banner and Interstital Ad) on my phone. 
  2.Millennial show errorCode:5. 
  3.Google No messages are displayed



 




------------------ 原始邮件 ------------------
发件人: "Eric Leichtenschlag";<notifications@github.com>;
发送时间: 2017年4月8日(星期六) 凌晨1:01
收件人: "googleads/googleads-mobile-android-examples"<googleads-mobile-android-examples@noreply.github.com>; 
抄送: "KEN"<378434243@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [googleads/googleads-mobile-android-examples] RewardedVideoAd：There was a problem getting an ad response. ErrorCode: 0 (#65)




Is there any chance you have the Creative Preview app installed on your device. That ad unit points to a rewarded video house ad campaign for this app and has the AdMob network turned off. If the app is installed, the ad is ineliglble, and no other ads are configured to serve to this ad unit.
 
I was just able to successfully run the rewarded sample in this repo on a device that didn't have this app installed.

**Comment by ericleich** [comment]
To clarify, did you already have Creative preview installed when I asked 3 days ago? If the creative preview app is installed, then `ca-app-pub-3940256099942544/5224354917` won't work, because the only ad it's set up to serve (an ad for the Creative Preview app) gets filtered out because you already have that app installed.

If you create your own rewarded ad unit ID under an Android app, it should start serving after ~1 hour. It takes about an hour for a newly created ad unit to start serving ads.

**Comment by LoveMyBaby** [comment]
Thanks!!!
 




------------------ 原始邮件 ------------------
发件人: "Eric Leichtenschlag";<notifications@github.com>;
发送时间: 2017年4月11日(星期二) 凌晨3:18
收件人: "googleads/googleads-mobile-android-examples"<googleads-mobile-android-examples@noreply.github.com>; 
抄送: "KEN"<378434243@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [googleads/googleads-mobile-android-examples] RewardedVideoAd：There was a problem getting an ad response. ErrorCode: 0 (#65)




To clarify, did you already have Creative preview installed when I asked 3 days ago? If the creative preview app is installed, then ca-app-pub-3940256099942544/5224354917 won't work, because the only ad it's set up to serve (an ad for the Creative Preview app) gets filtered out because you already have that app installed.
 
If you create your own rewarded ad unit ID under an Android app, it should start serving after ~1 hour. It takes about an hour for a newly created ad unit to start serving ads.
