### ISSUE TITLE
after view Second Reward ads is complete i got this error "Invalid event ID: null"

### ISSUE THREAD

**Issue by zeeid** [googleads/googleads-mobile-android-examples#655]
![image](https://github.com/googleads/googleads-mobile-android-examples/assets/79952361/42fe9946-d080-46cc-8949-f22b86e8b457)

`Invalid event ID: null
                                                                                                    java.lang.NumberFormatException: Cannot parse null string
                                                                                                    	at java.lang.Long.parseLong(Long.java:714)
                                                                                                    	at java.lang.Long.parseLong(Long.java:876)
                                                                                                    	at com.google.android.gms.internal.ads.zzbzs.zzB(com.google.android.gms:play-services-ads@@22.6.0:3)
                                                                                                    	at com.google.android.gms.internal.ads.zzbzs.zzo(com.google.android.gms:play-services-ads@@22.6.0:6)
                                                                                                    	at com.google.android.gms.internal.ads.zzdil.zzbx(com.google.android.gms:play-services-ads@@22.6.0:3)
                                                                                                    	at com.google.android.gms.internal.ads.zzczn.zza(com.google.android.gms:play-services-ads@@22.6.0:1)
                                                                                                    	at com.google.android.gms.internal.ads.zzddt.run(com.google.android.gms:play-services-ads@@22.6.0:1)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)`

Hello
is this oke ?
i Run **java/admob/RewardedVideoExample**
and Ads is Showing But After view Second Reward ads is complete i got this error

**Comment by NVentimiglia** [comment]
Please submit this report to the [SDK team](https://developers.google.com/admob/support).

**Comment by zeeid** [comment]
> Please submit this report to the [SDK team](https://developers.google.com/admob/support).

not helping the problem 😣
