### ISSUE TITLE
StrictMode policy violation

### ISSUE THREAD

**Issue by tmxdyf** [googleads/googleads-mobile-android-examples#686]
version:
com.google.android.gms:play-services-ads-base@@23.1.0:2

log:
`StrictMode policy violation: android.os.strictmode.IncorrectContextUseViolation: WindowManager should be accessed from Activity or other visual Context. Use an Activity or a Context created with Context#createWindowContext(int, Bundle), which are adjusted to the configuration and visual bounds of an area on screen.
                                                                                                    	at android.os.StrictMode.onIncorrectContextUsed(StrictMode.java:2260)
                                                                                                    	at android.app.ContextImpl.getSystemService(ContextImpl.java:2126)
                                                                                                    	at android.content.ContextWrapper.getSystemService(ContextWrapper.java:910)
                                                                                                    	at com.google.android.gms.ads.internal.activeview.f.<init>(:com.google.android.gms.policy_ads_fdr_dynamite@241199803@241199801034.618989241.618989241:34)
                                                                                                    	at com.google.android.gms.ads.nonagon.ad.event.fx.i(:com.google.android.gms.policy_ads_fdr_dynamite@241199803@241199801034.618989241.618989241:16)
                                                                                                    	at com.google.android.gms.ads.nonagon.ad.nativead.q.s(:com.google.android.gms.policy_ads_fdr_dynamite@241199803@241199801034.618989241.618989241:22)
                                                                                                    	at com.google.android.gms.ads.nonagon.ad.nativead.an.A(:com.google.android.gms.policy_ads_fdr_dynamite@241199803@241199801034.618989241.618989241:38)
                                                                                                    	at com.google.android.gms.ads.nonagon.ad.nativead.an.z(:com.google.android.gms.policy_ads_fdr_dynamite@241199803@241199801034.618989241.618989241:28)
                                                                                                    	at com.google.android.gms.ads.nonagon.ad.nativead.bn.bN(:com.google.android.gms.policy_ads_fdr_dynamite@241199803@241199801034.618989241.618989241:39)
                                                                                                    	at com.google.android.gms.ads.internal.formats.client.l.bS(:com.google.android.gms.policy_ads_fdr_dynamite@241199803@241199801034.618989241.618989241:213)
                                                                                                    	at m.alw.onTransact(:com.google.android.gms.policy_ads_fdr_dynamite@241199803@241199801034.618989241.618989241:21)
                                                                                                    	at android.os.Binder.transact(Binder.java:1169)
                                                                                                    	at com.google.android.gms.internal.ads.zzazo.zzdc(com.google.android.gms:play-services-ads-base@@23.1.0:2)
                                                                                                    	at com.google.android.gms.internal.ads.zzbhg.zzdz(com.google.android.gms:play-services-ads-lite@@23.1.0:3)
                                                                                                    	at com.google.android.gms.ads.nativead.NativeAdView.setNativeAd(com.google.android.gms:play-services-ads-lite@@23.1.0:1)
                                                                                                    	at com.google.android.ads.nativetemplates.TemplateView.setNativeAd(TemplateView.kt:207)`

**Comment by NVentimiglia** [comment]
@tmxdyf Can you share your implementation and steps you took to generate this error ? I have not seen this error before.
