### ISSUE TITLE
NativeAdvancedExample: The following classes could not be instantiated:

### ISSUE THREAD

**Issue by mingqiuwang** [googleads/googleads-mobile-android-examples#69]
When open ad_content.xml, it shows error under Design mode.

The following classes could not be instantiated:
- com.google.android.gms.ads.formats.NativeContentAdView (Open Class, Show Exception, Clear Cache)
 Tip: Use View.isInEditMode() in your custom views to skip code or show sample data when shown in the IDE.  If this is an unexpected error you can also try to build the project, then manually refresh the layout.

java.lang.IllegalStateException: A required meta-data tag in your app's AndroidManifest.xml does not exist.  You must have the following declaration within the <application> element:     <meta-data android:name="com.google.android.gms.version" android:value="@integer/google_play_services_version" />
	at com.google.android.gms.common.zzg.zzaH(Unknown Source)
	at com.google.android.gms.common.zzg.isGooglePlayServicesAvailable(Unknown Source)
	at com.google.android.gms.common.zze.isGooglePlayServicesAvailable(Unknown Source)
	at com.google.android.gms.internal.zzqe.zzaf(Unknown Source)
	at com.google.android.gms.internal.zzek.zza(Unknown Source)
	at com.google.android.gms.internal.zzek.zza(Unknown Source)
	at com.google.android.gms.ads.formats.NativeAdView.zzbv(Unknown Source)
	at com.google.android.gms.ads.formats.NativeAdView.<init>(Unknown Source)
	at com.google.android.gms.ads.formats.NativeContentAdView.<init>(Unknown Source)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.jetbrains.android.uipreview.ViewLoader.createNewInstance(ViewLoader.java:475)
	at org.jetbrains.android.uipreview.ViewLoader.loadClass(ViewLoader.java:262)
	at org.jetbrains.android.uipreview.ViewLoader.loadView(ViewLoader.java:220)
	at com.android.tools.idea.rendering.LayoutlibCallbackImpl.loadView(LayoutlibCallbackImpl.java:186)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:334)
	at android.view.BridgeInflater.loadCustomView(BridgeInflater.java:345)
	at android.view.BridgeInflater.createViewFromTag(BridgeInflater.java:245)
	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:727)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:495)
	at android.view.LayoutInflater.inflate(LayoutInflater.java:397)
	at com.android.layoutlib.bridge.impl.RenderSessionImpl.inflate(RenderSessionImpl.java:324)
	at com.android.layoutlib.bridge.Bridge.createSession(Bridge.java:429)
	at com.android.ide.common.rendering.LayoutLibrary.createSession(LayoutLibrary.java:368)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:567)
	at com.android.tools.idea.rendering.RenderTask$2.compute(RenderTask.java:549)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:863)
	at com.android.tools.idea.rendering.RenderTask.createRenderSession(RenderTask.java:549)
	at com.android.tools.idea.rendering.RenderTask.lambda$inflate$1(RenderTask.java:680)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ericleich** [comment]
This is a bug but it is against the Google Mobile Ads SDK itself, not the samples. Can you report this through the [Google Mobile Ads SDK developer forum](https://groups.google.com/group/google-admob-ads-sdk)?

**Comment by ericleich** [comment]
Closing as this is an SDK issue, not examples issue.
