### ISSUE TITLE
Cannot load ad open successfully when app uses overlay on xiaomi, pixel 8 still work normally

### ISSUE THREAD

**Issue by ChungHa136** [googleads/googleads-mobile-android-examples#733]
Application attempted to call on a destroyed WebView
                 java.lang.Throwable
                 	at org.chromium.android_webview.AwContents.t(chromium-TrichromeWebViewGoogle6432.aab-stable-647813533:10)
                 	at com.android.webview.chromium.WebViewChromium.setBackgroundColor(chromium-TrichromeWebViewGoogle6432.aab-stable-647813533:46)
                 	at android.webkit.WebView.setBackgroundColor(WebView.java:3023)
                 	at com.google.android.gms.ads.internal.webview.ab.ae(:com.google.android.gms.policy_ads_fdr_dynamite@)
                 	at com.google.android.gms.ads.internal.overlay.l.x(:com.google.android.gms.policy_ads_fdr_dynamite@)
                 	at com.google.android.gms.ads.internal.overlay.l.d(:com.google.android.gms.policy_ads_fdr_dynamite)
                 	at com.google.android.gms.ads.internal.overlay.client.a.bV(:com.google.android.gms.policy_ads_fdr_dynamit5)
                 	at m.amo.onTransact(:com.google.android.gms.policy_ads_fdr_dynamite@)
                 	at android.os.Binder.transact(Binder.java:1169)
                 	at com.google.android.gms.internal.ads.zzazo.zzdc(SourceFile:8)
                 	at com.google.android.gms.internal.ads.zzbun.zzl(SourceFile:9)
                 	at com.google.android.gms.ads.AdActivity.onCreate(SourceFile:18)
                 	at android.app.Activity.performCreate(Activity.java:8538)
                 	at android.app.Activity.performCreate(Activity.java:8502)
                 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1437)
                 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3878)
                 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4043)
                 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:101)
                 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
                 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
                 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2437)
                 	at android.os.Handler.dispatchMessage(Handler.java:106)
                 	at android.os.Looper.loopOnce(Looper.java:211)
                 	at android.os.Looper.loop(Looper.java:300)
                 	at android.app.ActivityThread.main(ActivityThread.java:8294)
                 	at java.lang.reflect.Method.invoke(Native Method)
                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
17:36:15.332  W  #004 The webview is destroyed. Ignoring action.
17:36:15.342  W  The webview does not exist. Ignoring action

[Xiaomi Poco X5]

![image](https://github.com/user-attachments/assets/d9ef3134-f426-4958-99cb-5e76e8d00482)

**Comment by hahashigehaha** [comment]
I have the same problem. Have you solved it?

**Comment by malandr2** [comment]
Hi @ChungHa136, for us to properly triage your issue, please create a new thread in the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk). From there, we can begin the troubleshooting process. Closing this out as next steps will take place in the forum - thanks!
