### ISSUE TITLE
Unknown calling package name 'com.google.android.gms'.

### ISSUE THREAD

**Issue by SaimaUsman0333** [googleads/googleads-mobile-android-examples#771]
I am trying to show App Open Ad in my android app in the beginning of the app. The issue I am facing is that in the first run it says:

Failed to get service from broker. 
java.lang.SecurityException: Unknown calling package name 'com.google.android.gms'.
	at android.os.Parcel.createExceptionOrNull(Parcel.java:2390)
	at android.os.Parcel.createException(Parcel.java:2374)
	at android.os.Parcel.readException(Parcel.java:2357)
	at android.os.Parcel.readException(Parcel.java:2299)
	at alvr.a(:com.google.android.gms@244433022@24.44.33 (150400-694629214):36)
	at alty.z(:com.google.android.gms@244433022@24.44.33 (150400-694629214):150)
	at albi.run(:com.google.android.gms@244433022@24.44.33 (150400-694629214):54)
	at android.os.Handler.handleCallback(Handler.java:938)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at bqws.lR(:com.google.android.gms@244433022@24.44.33 (150400-694629214):1)
	at bqws.dispatchMessage(:com.google.android.gms@244433022@24.44.33 (150400-694629214):5)
	at android.os.Looper.loop(Looper.java:264)
	at android.os.HandlerThread.run(HandlerThread.java:67)

Unable to search this issue over the internet so posting here.

**Comment by sanoj26692** [comment]
I get the following error while trying to load a `Interstitial Ad` But when i tried the same code in empty activity without activity code ad was loaded and Showen. I used the same code listed here [https://github.com/googleads/googleads-mobile-android-examples/tree/main/java/admob/InterstitialExample](url)
`FATAL EXCEPTION: main
                                                                                                    Process: com.jldevelopers.jlplayer, PID: 24776
                                                                                                    java.lang.IllegalArgumentException: Parcel: unknown type for value com.google.android.gms.internal.ads.zzbsp@19c767a
                                                                                                    	at android.os.Parcel.getValueType(Parcel.java:2409)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2308)
                                                                                                    	at android.os.Parcel.writeList(Parcel.java:1382)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2460)
                                                                                                    	at android.os.Parcel.writeValue(Parcel.java:2316)
                                                                                                    	at android.os.BaseBundle.dumpStats(BaseBundle.java:1874)
                                                                                                    	at android.os.BaseBundle.dumpStats(BaseBundle.java:1911)
                                                                                                    	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:152)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:942)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:211)
                                                                                                    	at android.os.Looper.loop(Looper.java:300)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8503)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)`

**Comment by malandr2** [comment]
Hi @SaimaUsman0333 and @sanoj26692, to properly triage your issue if you could create a new thread in the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk). From there we can start the troubleshooting process.

Closing this out - thanks!
