### ISSUE TITLE
ANR due to long running binder transaction on main thread due to volume change by user

### ISSUE THREAD

**Issue by Arthas26** [googleads/googleads-mobile-android-examples#772]
As the title suggests, i have seen these anr in one of my apps. 
The ContentObserver can be easily configured to have a non ui handler thread so that binder transaction in onChange can offloaded to a non ui thread. 

Also if this is not the right place to report this issues , pls point me in the right direction.

Stack Trace

 ```
main (native):tid=1 systid=8472 
#00 pc 0x4b38c libc.so (syscall + 28)
#01 pc 0x1af92c libart.so (art::ConditionVariable::WaitHoldingLocks(art::Thread*) + 148)
#02 pc 0x66b4b4 libart.so (art::GoToRunnable(art::Thread*) + 460)
#03 pc 0x66b2a4 libart.so (art::JniMethodEnd(unsigned int, art::Thread*) + 28)
       at android.os.BinderProxy.transactNative(Native method)
       at android.os.BinderProxy.transact(BinderProxy.java:540)
       at android.media.IAudioService$Stub$Proxy.getStreamVolume(IAudioService.java:2735)
       at android.media.AudioManager.getStreamVolume(AudioManager.java:1026)
       at com.google.android.gms.ads.omid.library.devicevolume.b.a(:com.google.android.gms.policy_ads_fdr_dynamite@243799214@243799204017.685849251.685849251:4)
       at com.google.android.gms.ads.omid.library.devicevolume.b.onChange(:com.google.android.gms.policy_ads_fdr_dynamite@243799214@243799204017.685849251.685849251:4)
       at android.database.ContentObserver.onChange(ContentObserver.java:153)
       at android.database.ContentObserver.onChange(ContentObserver.java:169)
       at android.database.ContentObserver.onChange(ContentObserver.java:187)
       at android.database.ContentObserver.onChange(ContentObserver.java:202)
       at android.database.ContentObserver.lambda$dispatchChange$0$ContentObserver(ContentObserver.java:282)
       at android.database.-$$Lambda$ContentObserver$MgqiYb2qvgLhoXTioYXq9MvvpNk.run(lambda)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:250)
       at android.app.ActivityThread.main(ActivityThread.java:7806)
       at java.lang.reflect.Method.invoke(Native method)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:958)
        
```

**Comment by malandr2** [comment]
Hi @Arthas26, to properly triage your issue if you could create a new thread in the [AdMob Developers forum](https://groups.google.com/g/google-admob-ads-sdk). From there we can start the troubleshooting process.

Closing this out - thanks!
