### ISSUE TITLE
Exception(Results have already been set)

### ISSUE THREAD

**Issue by HaloMego** [googleads/googleads-mobile-android-examples#99]
Hello,sir,I had tried my best to search the exception via search engine,but now i  can still not  solve the exception.the version of sdk is **11.0.4**,the following snippet is stack trace .   

> Exception java.lang.IllegalStateException: Results have already been set
com.google.android.gms.common.internal.zzbo.zza ()
com.google.android.gms.internal.zzbbl.setResult ()
com.google.android.gms.internal.zzbbf.zzz ()
com.google.android.gms.internal.zzbbf.zzf ()
com.google.android.gms.internal.zzbbf.zzb ()
com.google.android.gms.internal.zzbav.zza ()
com.google.android.gms.internal.zzbdk.zzb ()
com.google.android.gms.internal.zzbdk.zzrR ()
com.google.android.gms.internal.zzbdk.onConnected ()
com.google.android.gms.common.internal.zzaa.onConnected$51662RJ4E9NMIP1FDTPIUGJLDPI6OP9R55B0____0 ()
com.google.android.gms.common.internal.zzn.zzsR ()
com.google.android.gms.common.internal.zze.zzy ()
com.google.android.gms.common.internal.zzh.handleMessage ()
android.os.Handler.dispatchMessage (Handler.java:111)
android.os.Looper.loop (Looper.java:207)
android.os.HandlerThread.run (HandlerThread.java:61)

**Comment by mutour** [comment]
遇到同样问题，11.6.0版本


java.lang.IllegalStateException: Results have already been set
	at com.google.android.gms.common.internal.zzbo.zza(Unknown Source)
	at com.google.android.gms.internal.zzbbl.setResult(Unknown Source)
	at com.google.android.gms.internal.zzbbf.zzz(Unknown Source)
	at com.google.android.gms.internal.zzbbf.zzf(Unknown Source)
	at com.google.android.gms.internal.zzbbf.zzb(Unknown Source)
	at com.google.android.gms.internal.zzbav.zza(Unknown Source)
	at com.google.android.gms.internal.zzbdk.zzb(Unknown Source)
	at com.google.android.gms.internal.zzbdk.zzrR(Unknown Source)
	at com.google.android.gms.internal.zzbdk.onConnected(Unknown Source)
	at com.google.android.gms.common.internal.zzaa.onConnected$51662RJ4E9NMIP1FDTPIUGJLDPI6OP9R55B0____0(Unknown Source)
	at com.google.android.gms.common.internal.zzn.zzsR(Unknown Source)
	at com.google.android.gms.common.internal.zze.zzy(Unknown Source)
	at com.google.android.gms.common.internal.zzh.handleMessage(Unknown Source)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:148)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by stowy** [comment]
Hi, thanks for your query.

These github issues are for issues with the sample apps only, for support debugging your apps, can we request that you make a request on our [support forum](https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android) at https://groups.google.com/forum/#!categories/google-admob-ads-sdk/android - they will be able to help debug your issue with you efficiently.

When posting to the forum, please also provide specific details including any errors being seen and code showing how to reproduce the problem.

If you have a specific issue with a sample app, please provide details including which sample app and specific steps to reproduce the issue.

Thanks,

Sam

**Comment by lizheng98** [comment]
I encountered the same problem in version 11.8.0.
java.lang.IllegalStateException: Results have already been set
at com.google.android.gms.common.internal.zzbo.zza(Unknown Source)
at com.google.android.gms.internal.zzbbl.setResult(Unknown Source)
at com.google.android.gms.internal.zzbbf.zzz(Unknown Source)
at com.google.android.gms.internal.zzbbf.zzf(Unknown Source)
at com.google.android.gms.internal.zzbbf.zzb(Unknown Source)
at com.google.android.gms.internal.zzbav.zza(Unknown Source)
at com.google.android.gms.internal.zzbdk.zzb(Unknown Source)
at com.google.android.gms.internal.zzbdk.zzrR(Unknown Source)
at com.google.android.gms.internal.zzbdk.onConnected(Unknown Source)
at com.google.android.gms.common.internal.zzaa.onConnected$51662RJ4E9NMIP1FDTPIUGJLDPI6OP9R55B0____0(Unknown Source)
at com.google.android.gms.common.internal.zzn.zzsR(Unknown Source)
at com.google.android.gms.common.internal.zze.zzy(Unknown Source)
at com.google.android.gms.common.internal.zzh.handleMessage(Unknown Source)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by lizheng98** [comment]
@HaloMego 你好，请问您这个问题解决了吗？ 能帮忙我一下么

**Comment by stowy** [comment]
Hi,

Thanks, this is a known issue, you can track it at https://issuetracker.google.com/issues/70416429, it is not specific to the ads SDK. Please follow that bug to be updated about resolution.

There is also a [thread on the support forum](https://groups.google.com/forum/#!searchin/google-admob-ads-sdk/java.lang.IllegalStateException$3A$20Results$20have$20already$20been$20set%7Csort:date/google-admob-ads-sdk/DpJX7fLA8as/6Ldc-OZ3CwAJ) regarding this.

**Comment by lizheng98** [comment]
@stowy 
 hi,
 https://issuetracker.google.com/issues/70416429，This link is all about throwing the problem, not the solution.

**Comment by HaloMego** [comment]
@lizheng98 目前还没有解决。

**Comment by stowy** [comment]
Correct. The link is for an issue tracker, it is a known issue with the GMS core library. When the team has a resolution available, the issue tracker will be update.

**Comment by lizheng98** [comment]
ok ，thank you

**Comment by stowy** [comment]
no problem, thanks.
